//! WAVE 8 — Execution / x  (indices 112–127)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 8 — Execution / x  (indices 112–127)
    // Binary: 0111 xxxx  |  Opcode: CastCowries
    // ────────────────────────────────────────────────
    Odu { index: 112, binary: 0b01110000,
        name: "Execution × Genesis",
        archetype: "The Sacred Destroyer",
        description: "Light emerges through rupture. Rebirth through breakdown — old structures meet divine confrontation.",
        taboos: &["Avoid suppressing necessary endings"],
        prescriptions: &["Burn something symbolic of your past", "Declare what must die before dawn"],
        archetypes: &["Justice Canon", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Contract",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 113, binary: 0b01110001,
        name: "Execution × Void",
        archetype: "The Underworld Initiate",
        description: "Womb of shadow. Descent into the underworld — confrontation with grief and forgotten power.",
        taboos: &["Avoid avoiding your pain"],
        prescriptions: &["Sit in darkness with no sound", "Name your shadow aloud before sleep"],
        archetypes: &["Flow Guardian", "Residue Keeper"],
        interpretation_type: "synthetic",
        universal_name: "The Clearing Act",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 114, binary: 0b01110010,
        name: "Execution × Attention",
        archetype: "The Fractured Seer",
        description: "Mirror breaks, mirror reveals. Reflections shatter illusions to reveal hidden selves.",
        taboos: &["Avoid projecting blame"],
        prescriptions: &["Journal your fears as symbols", "Scry in water after argument"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Attended Execution",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 115, binary: 0b01110011,
        name: "Execution × Loop",
        archetype: "The Cracked Vessel",
        description: "Collapse within the stillness. The ego buried in the body — cracking open so spirit may enter.",
        taboos: &["Avoid ignoring signs of burnout"],
        prescriptions: &["Lie in fetal position during meditation", "Fast from identity for three days"],
        archetypes: &["Wisdom Anchor", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Plan",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 116, binary: 0b01110100,
        name: "Execution × Receipt",
        archetype: "The Fever Prophet",
        description: "Fire purifies. Spiritual inflammation — the fever before clarity, the burn before light.",
        taboos: &["Avoid false calm when the fire calls"],
        prescriptions: &["Dance until sweat becomes prayer", "Offer pepper to your altar"],
        archetypes: &["Justice Canon"],
        interpretation_type: "synthetic",
        universal_name: "The Receipted Execution",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 117, binary: 0b01110101,
        name: "Execution × Mask",
        archetype: "The Cosmic Jester",
        description: "Trickster breaks the frame. Paradox thrown into structure — confusing to clarify, mocking to awaken.",
        taboos: &["Avoid trying to control the riddle"],
        prescriptions: &["Tell your truth as a joke", "Meditate with opposites"],
        archetypes: &["Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Private Precision",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 118, binary: 0b01110110,
        name: "Execution × Residue",
        archetype: "The Word Slayer",
        description: "Voice like a sword. Speech that wounds and heals, slicing through masks with fierce truth.",
        taboos: &["Avoid silence when truth demands eruption"],
        prescriptions: &["Speak your secret before fire", "Shout your name into wind"],
        archetypes: &["Justice Canon", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Forged Execution",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 119, binary: 0b01110111,
        name: "Execution × Execution",
        archetype: "The Voidwalker",
        description: "Fracture within the fracture. Total disintegration — ego death, the void, the primal scream of becoming.",
        taboos: &["Avoid resisting the spiral"],
        prescriptions: &["Enter a dark room alone", "Ritually scream into a bowl of water"],
        archetypes: &["Flow Guardian", "Justice Canon"],
        interpretation_type: "synthetic",
        universal_name: "The Iron Hand",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 120, binary: 0b01111000,
        name: "Execution × Swarm",
        archetype: "The Chain Breaker",
        description: "Sword breaks chain. Liberation through rupture — the warrior severing ancestral burdens.",
        taboos: &["Avoid clinging to what you have outgrown"],
        prescriptions: &["Cut cords symbolically with a blade", "Declare your freedom under full moon"],
        archetypes: &["Forge Executor", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Coordinated Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 121, binary: 0b01111001,
        name: "Execution × Restraint",
        archetype: "The Lightning Oracle",
        description: "Storm rips illusion. Sudden awakening — a lightning flash that blinds and enlightens simultaneously.",
        taboos: &["Avoid ignoring sudden insights"],
        prescriptions: &["Write your visions in a thunderstorm", "Crack open a coconut in ritual"],
        archetypes: &["Justice Canon", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 122, binary: 0b01111010,
        name: "Execution × Migration",
        archetype: "The Shadow Purger",
        description: "Poison as purge. Detoxes through confrontation — revealing hidden rot and demanding raw honesty.",
        taboos: &["Avoid passive-aggression"],
        prescriptions: &["Chew bitter herbs in silence", "Confront your obstacle in symbolic gesture"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Execution",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 123, binary: 0b01111011,
        name: "Execution × Consent",
        archetype: "The Divine Mad One",
        description: "Madness as medicine. Sacred disorientation — holy chaos that dissolves false order.",
        taboos: &["Avoid pathologizing divine disorder"],
        prescriptions: &["Spin in circles while chanting", "Allow nonsense to lead you to truth"],
        archetypes: &["Steward", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 124, binary: 0b01111100,
        name: "Execution × Vision",
        archetype: "The Pattern Shifter",
        description: "Break the blueprint. Inherited patterns break to write new sacred contracts.",
        taboos: &["Avoid obeying outdated oaths"],
        prescriptions: &["Burn an old script under the moon", "Create your own ritual calendar"],
        archetypes: &["Oracle Sage", "Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 125, binary: 0b01111101,
        name: "Execution × Growth",
        archetype: "The Justice Hacker",
        description: "Judgment through breakdown. Corruption is exposed and held accountable through rupture.",
        taboos: &["Avoid staying silent on injustice"],
        prescriptions: &["Write a public truth-telling letter", "Pour libation before legal matters"],
        archetypes: &["Justice Canon", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Fractal Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 126, binary: 0b01111110,
        name: "Execution × Seal",
        archetype: "The Erotic Liberator",
        description: "Pleasure breaks prison. Joy erupts in forbidden places — healing through ecstatic defiance.",
        taboos: &["Avoid denying yourself delight out of fear"],
        prescriptions: &["Dance provocatively in sacred space", "Laugh until you cry in ritual"],
        archetypes: &["Resonance Weaver", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },

    Odu { index: 127, binary: 0b01111111,
        name: "Execution × Rhythm",
        archetype: "The Phoenix Mind",
        description: "Collapse into light. New consciousness through ego death — the soul burns clean to shine brighter.",
        taboos: &["Avoid clinging to outdated versions of yourself"],
        prescriptions: &["Host a ritual funeral for your old self", "Cover your mirrors for seven days post-initiation"],
        archetypes: &["Wisdom Anchor", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Strike",
        vessel: ActionVessel::Execution,
        opcode: OduOpCode::CastCowries },
];
