//! WAVE 14 — Ìrẹtẹ̀ Méjì / x  (indices 208–223)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 14 — Ìrẹtẹ̀ Méjì / x  (indices 208–223)
    // Binary: 1101 xxxx  |  Opcode: Dup
    // ────────────────────────────────────────────────
    Odu { index: 208, binary: 0b11010000,
        name: "Ìrẹtẹ̀ Méjì / Ẹ̀jì Ogbe",
        archetype: "The Patient Guardian",
        description: "Patience nurtures success. The power of steady progress and waiting for the right moment.",
        taboos: &["Avoid impatience and haste"],
        prescriptions: &["Practice daily mindfulness", "Offer libations for timing"],
        orisha: &["Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Seed",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 209, binary: 0b11010001,
        name: "Ìrẹtẹ̀ Méjì / Òyèkú Méjì",
        archetype: "The Silent Observer",
        description: "Balance within darkness. Strength in stillness and acceptance of the unknown.",
        taboos: &["Avoid resisting darkness"],
        prescriptions: &["Meditate in silence", "Light black candles with reverence"],
        orisha: &["Ọ̀yá", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Void Pruning",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 210, binary: 0b11010010,
        name: "Ìrẹtẹ̀ Méjì / Ìwòrì Méjì",
        archetype: "The Harmonious Seer",
        description: "Harmony in reflection. Inner balance achieved through thoughtful contemplation.",
        taboos: &["Avoid self-judgment"],
        prescriptions: &["Journal emotions", "Practice loving-kindness meditation"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Watching Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 211, binary: 0b11010011,
        name: "Ìrẹtẹ̀ Méjì / Òdí Méjì",
        archetype: "The Grounded Protector",
        description: "Calm foundation. Spirit stabilized through grounding and acceptance.",
        taboos: &["Avoid instability"],
        prescriptions: &["Practice grounding rituals", "Connect with earth energies"],
        orisha: &["Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Growth Loop",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 212, binary: 0b11010100,
        name: "Ìrẹtẹ̀ Méjì / Ìròsùn Méjì",
        archetype: "The Patient Purifier",
        description: "Purification through patience. Obstacles cleansed by waiting and enduring.",
        taboos: &["Avoid rushing healing"],
        prescriptions: &["Offer water to sacred fire", "Practice fasting with intention"],
        orisha: &["Ọ̀ṣun", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Ledger of Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 213, binary: 0b11010101,
        name: "Ìrẹtẹ̀ Méjì / Òwónrín Méjì",
        archetype: "The Graceful Jester",
        description: "Gentle trickster. Lessons softened with humor and grace.",
        taboos: &["Avoid harshness"],
        prescriptions: &["Use laughter in healing", "Tell sacred stories"],
        orisha: &["Èṣù", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Growing Mask",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 214, binary: 0b11010110,
        name: "Ìrẹtẹ̀ Méjì / Òbàrà Méjì",
        archetype: "The Compassionate Speaker",
        description: "Words of balance. Mindful speech and compassionate communication are taught.",
        taboos: &["Avoid harsh words"],
        prescriptions: &["Recite affirmations", "Practice active listening"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Memory of Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 215, binary: 0b11010111,
        name: "Ìrẹtẹ̀ Méjì / Ọ̀kànràn Méjì",
        archetype: "The Tempered Flame",
        description: "Fire tempered by patience. Passion refined through calm and control.",
        taboos: &["Avoid impulsiveness"],
        prescriptions: &["Meditate with candles", "Practice breath control"],
        orisha: &["Ṣàngó", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Decisive Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 216, binary: 0b11011000,
        name: "Ìrẹtẹ̀ Méjì / Ògúndá Méjì",
        archetype: "The Steady Warrior",
        description: "Steadfast strength. Power grounded in endurance and wisdom.",
        taboos: &["Avoid reckless force"],
        prescriptions: &["Practice martial discipline", "Offer iron in ritual"],
        orisha: &["Ògún", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 217, binary: 0b11011001,
        name: "Ìrẹtẹ̀ Méjì / Òsá Méjì",
        archetype: "The Serene Storm",
        description: "Calm storm. Chaos balanced with serene acceptance.",
        taboos: &["Avoid resisting change"],
        prescriptions: &["Meditate during storms", "Offer palm oil to Òsà"],
        orisha: &["Ọ̀yá", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 218, binary: 0b11011010,
        name: "Ìrẹtẹ̀ Méjì / Ìkà Méjì",
        archetype: "The Patient Healer",
        description: "Healing patience. Transformation guided through enduring care.",
        taboos: &["Avoid ignoring pain"],
        prescriptions: &["Use herbal remedies", "Journal healing journey"],
        orisha: &["Ọ̀ṣun", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 219, binary: 0b11011011,
        name: "Ìrẹtẹ̀ Méjì / Òtúrúpòn Méjì",
        archetype: "The Wise Guardian",
        description: "Wise patience. Calm understanding and ancestral guidance embodied.",
        taboos: &["Avoid impatience with tradition"],
        prescriptions: &["Honor elders", "Observe sacred cycles"],
        orisha: &["Ọ̀rúnmìlà", "Egúngún"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 220, binary: 0b11011100,
        name: "Ìrẹtẹ̀ Méjì / Òtúrá Méjì",
        archetype: "The Harmonious Creator",
        description: "Balanced creation. Structure and flow harmonize in sacred work.",
        taboos: &["Avoid chaos in ritual"],
        prescriptions: &["Maintain altar order", "Perform daily offerings"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Visionary Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 221, binary: 0b11011101,
        name: "Ìrẹtẹ̀ Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Balanced One",
        description: "The epitome of balance. Perfect harmony and patient strength fully embodied.",
        taboos: &["Avoid extremes"],
        prescriptions: &["Practice meditation", "Live with intention"],
        orisha: &["Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 222, binary: 0b11011110,
        name: "Ìrẹtẹ̀ Méjì / Òsé Méjì",
        archetype: "The Joyful Endurer",
        description: "Sweet patience. Joy combined with endurance creates lasting growth.",
        taboos: &["Avoid bitterness"],
        prescriptions: &["Celebrate small wins", "Offer honey in ritual"],
        orisha: &["Ọ̀ṣun", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },

    Odu { index: 223, binary: 0b11011111,
        name: "Ìrẹtẹ̀ Méjì / Òfún Méjì",
        archetype: "The Radiant Guardian",
        description: "Radiant patience. The path lit with gentle, enduring clarity.",
        taboos: &["Avoid haste"],
        prescriptions: &["Meditate on white light", "Offer white flowers"],
        orisha: &["Ọbàtálá", "Olódùmarè"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Growth",
        vessel: ActionVessel::Growth,
        opcode: OduOpCode::Dup },
];
