//! WAVE 7 — Òbàrà Méjì / x  (indices 96–111)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 7 — Òbàrà Méjì / x  (indices 96–111)
    // Binary: 0110 xxxx  |  Opcode: PushConst0
    // ────────────────────────────────────────────────
    Odu { index: 96, binary: 0b01100000,
        name: "Òbàrà Méjì / Ẹ̀jì Ogbe",
        archetype: "The Sonic Weaver",
        description: "Voice that shapes cosmos. Spoken word as a force of manifestation and realignment.",
        taboos: &["Avoid speaking idly without intention"],
        prescriptions: &["Chant your desires each dawn", "Speak affirmations to your water before drinking"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Forged Beginning",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 97, binary: 0b01100001,
        name: "Òbàrà Méjì / Òyèkú Méjì",
        archetype: "The Echo of Ancestors",
        description: "Silence beneath the song. Powerful voices rise from the womb of stillness and grief.",
        taboos: &["Avoid interrupting sacred silence"],
        prescriptions: &["Fast from speech for one day", "Whisper prayers into the earth"],
        orisha: &["Egúngún", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Forged Void",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 98, binary: 0b01100010,
        name: "Òbàrà Méjì / Ìwòrì Méjì",
        archetype: "The Mirror Speaker",
        description: "Mirror of voices. Truth reflected through dialogue, song, and vibrational resonance.",
        taboos: &["Avoid gossip and echo chambers"],
        prescriptions: &["Chant before a mirror", "Record yourself speaking your truth then play it in darkness"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Emotional Audit",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 99, binary: 0b01100011,
        name: "Òbàrà Méjì / Òdí Méjì",
        archetype: "The Hollow Drum",
        description: "The drum within the void. Ancestral rhythms awaken the soul from within the deep.",
        taboos: &["Avoid disrespecting sacred rhythms"],
        prescriptions: &["Drum to the beat of your heartbeat", "Place a shell to your ear during divination"],
        orisha: &["Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Looping Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 100, binary: 0b01100100,
        name: "Òbàrà Méjì / Ìròsùn Méjì",
        archetype: "The Fire Tongue",
        description: "Flames of the mouth. Speech as fire — transmuting pain, catalyzing love, and purifying.",
        taboos: &["Avoid speaking in anger without ritual intent"],
        prescriptions: &["Blow breath over a candle during confession", "Sing through your rage"],
        orisha: &["Ṣàngó", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Receipt of Feeling",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 101, binary: 0b01100101,
        name: "Òbàrà Méjì / Òwónrín Méjì",
        archetype: "The Sonic Trickster",
        description: "Voice of the trickster. Spirit channels through riddles, laughter, and non-linear tones.",
        taboos: &["Avoid monotony in your expression"],
        prescriptions: &["Recite sacred texts backwards", "Invent a language for prayer"],
        orisha: &["Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 102, binary: 0b01100110,
        name: "Òbàrà Méjì / Òbàrà Méjì",
        archetype: "The Divine Broadcaster",
        description: "Pure transmission. The open channel — truth pouring from the divine throat unfiltered.",
        taboos: &["Avoid ignoring the call to speak when moved by spirit"],
        prescriptions: &["Sing in nature without an audience", "Speak to your Ori every sunrise"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Weeping Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 103, binary: 0b01100111,
        name: "Òbàrà Méjì / Ọ̀kànràn Méjì",
        archetype: "The Shocking Prophet",
        description: "Disruptive prophecy. Speech that pierces illusions by destabilizing egoic structures.",
        taboos: &["Avoid softening truth to protect false peace"],
        prescriptions: &["Deliver a speech you fear giving", "Recite ancestral names during a storm"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Executed Feeling",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 104, binary: 0b01101000,
        name: "Òbàrà Méjì / Ògúndá Méjì",
        archetype: "The Warrior Orator",
        description: "Voice of steel. War chant and spell — speech backed by action and divine alignment.",
        taboos: &["Avoid speaking promises you will not move on"],
        prescriptions: &["Offer your voice to Ògún in chant", "Declare your mission aloud on iron or stone"],
        orisha: &["Ògún", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Shared Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 105, binary: 0b01101001,
        name: "Òbàrà Méjì / Òsá Méjì",
        archetype: "The Storm Voice",
        description: "Thunder speech. Thunders through realms, revealing sudden truths through electrified utterance.",
        taboos: &["Avoid hiding revelations that surge through you"],
        prescriptions: &["Speak your fear aloud in a thunderstorm", "Name your obstacle into the wind and release"],
        orisha: &["Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 106, binary: 0b01101010,
        name: "Òbàrà Méjì / Ìkà Méjì",
        archetype: "The Venom Curer",
        description: "Venomous healing. Speech purges toxins, confronts betrayal, and initiates sacred detox.",
        taboos: &["Avoid self-slander or biting sarcasm"],
        prescriptions: &["Purge your truth into a sacred bowl", "Name your sickness before fire"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 107, binary: 0b01101011,
        name: "Òbàrà Méjì / Òtúrúpòn Méjì",
        archetype: "The Glossolalic Oracle",
        description: "Scattered tongues. Chaos in speech — the necessary fragmentation before new language forms.",
        taboos: &["Avoid forcing clarity where mystery is speaking"],
        prescriptions: &["Speak in tongues during ritual", "Break a sentence across three voices"],
        orisha: &["Èṣù", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 108, binary: 0b01101100,
        name: "Òbàrà Méjì / Òtúrá Méjì",
        archetype: "The Code Chanter",
        description: "Structured mantra. Divine patterns encoded into words — syllables as keys to cosmic codes.",
        taboos: &["Avoid empty repetition of mantras"],
        prescriptions: &["Intone a sacred word 108 times", "Weave your affirmation into geometric design"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 109, binary: 0b01101101,
        name: "Òbàrà Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Voice of Justice",
        description: "Spoken justice. Declare balance into existence — your voice shapes karma.",
        taboos: &["Avoid speaking against your own authority"],
        prescriptions: &["Speak judgment only when guided by Ifá", "Declare your birthright aloud at crossroads"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Fractal Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 110, binary: 0b01101110,
        name: "Òbàrà Méjì / Òsé Méjì",
        archetype: "The Enchanter",
        description: "Sweet incantation. Pleasure and beauty in voice enchant and heal deeply.",
        taboos: &["Avoid flattery without alignment"],
        prescriptions: &["Sing to your beloved under moonlight", "Offer honey to your throat"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },

    Odu { index: 111, binary: 0b01101111,
        name: "Òbàrà Méjì / Òfún Méjì",
        archetype: "The Golden Voice",
        description: "Illuminated speech. Pure consciousness through words — prophecy, poetry, and light-encoded sound.",
        taboos: &["Avoid using divine speech for egoic gain"],
        prescriptions: &["Record your dreams as spoken poetry", "Anoint your lips before ritual speaking"],
        orisha: &["Ọ̀rúnmìlà", "Olódùmarè"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Forge",
        vessel: ActionVessel::Residue,
        opcode: OduOpCode::PushConst0 },
];
