//! WAVE 1 — Ẹ̀jì Ogbe / x  (indices 0–15)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 1 — Ẹ̀jì Ogbe / x  (indices 0–15)
    // Binary: 0000 xxxx  |  Opcode: PushConst1
    // ────────────────────────────────────────────────
    Odu { index: 0, binary: 0b00000000,
        name: "Ẹ̀jì Ogbe / Ẹ̀jì Ogbe",
        archetype: "The Divine Blueprint",
        description: "The first Odù, origin of all existence. Divine alignment, pure potential, and cosmic order.",
        taboos: &["Avoid lies", "Never break promises"],
        prescriptions: &["Offer coconut and water at dawn", "Meditate at sunrise"],
        orisha: &["Olódùmarè", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Light of First Becoming",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 1, binary: 0b00000001,
        name: "Ẹ̀jì Ogbe / Òyèkú Méjì",
        archetype: "The Twilight Veil",
        description: "Balance between light and shadow. Trust divine timing between revelation and concealment.",
        taboos: &["Avoid secrecy with trusted allies", "Do not ignore ancestral dreams"],
        prescriptions: &["Light one white and one black candle at twilight", "Leave offerings at crossroads during new moon"],
        orisha: &["Ọ̀ṣun", "Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "Genesis Into the Void",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 2, binary: 0b00000010,
        name: "Ẹ̀jì Ogbe / Ìwòrì Méjì",
        archetype: "The Ancestral Messenger",
        description: "Destiny unfolds like a scroll. Ancestral messages and the power of words to shape fate.",
        taboos: &["Do not gossip", "Avoid sharp or cursing speech"],
        prescriptions: &["Light incense for ancestors", "Read sacred texts aloud"],
        orisha: &["Ọ̀rúnmìlà", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "Covenant of the Inward Eye",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 3, binary: 0b00000011,
        name: "Ẹ̀jì Ogbe / Òdí Méjì",
        archetype: "The Sacred Womb",
        description: "A wellspring of creativity and transformation. Birth, initiation, and hidden strength.",
        taboos: &["Avoid suppressing your inner voice"],
        prescriptions: &["Offer fresh fruits", "Sit near running water"],
        orisha: &["Ọ̀ṣun", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Beginning",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 4, binary: 0b00000100,
        name: "Ẹ̀jì Ogbe / Ìròsùn Méjì",
        archetype: "The Lineage Healer",
        description: "Ancestral unrest and unfinished contracts. Lineage wounds call for repair and honoring of bloodlines.",
        taboos: &["Avoid disrespecting family elders"],
        prescriptions: &["Feed the ancestors", "Repair or clean a grave site"],
        orisha: &["Yemọja", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Accountable Genesis",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 5, binary: 0b00000101,
        name: "Ẹ̀jì Ogbe / Òwónrín Méjì",
        archetype: "The Trickster Oracle",
        description: "Warnings through dreams. Trickster energy, mental agility, and divine riddles awaiting decoding.",
        taboos: &["Avoid ignoring intuition"],
        prescriptions: &["Write down your dreams", "Light three candles before bed"],
        orisha: &["Èṣù", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Two-Faced Origin",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 6, binary: 0b00000110,
        name: "Ẹ̀jì Ogbe / Òbàrà Méjì",
        archetype: "The Golden Voice",
        description: "Joy, community, and celebration — but beware overindulgence. Charisma needs spiritual discipline.",
        taboos: &["Avoid pride or vanity"],
        prescriptions: &["Dance or sing to elevate energy", "Offer honey to Ọ̀ṣun"],
        orisha: &["Ọ̀ṣun", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Forged Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 7, binary: 0b00000111,
        name: "Ẹ̀jì Ogbe / Ọ̀kànràn Méjì",
        archetype: "The Divine Disruptor",
        description: "Sudden disruption for higher realignment. Okanran breaks illusions to reveal radical clarity.",
        taboos: &["Do not delay important decisions"],
        prescriptions: &["Draw a sigil on your threshold", "Offer tobacco to Èṣù"],
        orisha: &["Èṣù", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Executed Promise",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 8, binary: 0b00001000,
        name: "Ẹ̀jì Ogbe / Ògúndá Méjì",
        archetype: "The Path-Clearing Blade",
        description: "The warrior's path. Ogunda clears obstacles with fire and steel — protection, courage, divine motion.",
        taboos: &["Avoid cowardice", "Do not insult warriors"],
        prescriptions: &["Offer palm oil to Ògún", "Sharpen your tools — spiritual or physical"],
        orisha: &["Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Storm-Tested Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 9, binary: 0b00001001,
        name: "Ẹ̀jì Ogbe / Òsá Méjì",
        archetype: "The Karmic Mirror",
        description: "Karmic cycles, secrets, and ancestral tests. What is hidden will come to light.",
        taboos: &["Avoid binding spells", "Do not ignore repeating signs"],
        prescriptions: &["Perform an ancestral bath", "Burn palm fronds and speak your truth"],
        orisha: &["Ọ̀yá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Origin",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 10, binary: 0b00001010,
        name: "Ẹ̀jì Ogbe / Ìkà Méjì",
        archetype: "The Spiral Teacher",
        description: "The snake coil of destiny — slow, winding, potent. Warns against self-sabotage and gossip.",
        taboos: &["Avoid speaking ill of others"],
        prescriptions: &["Fast for one day in silence", "Offer black cloth to your shrine"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 11, binary: 0b00001011,
        name: "Ẹ̀jì Ogbe / Òtúrúpòn Méjì",
        archetype: "The Chaotic Prophet",
        description: "Unstable yet visionary. Mental conflict yields revelation only to the prepared.",
        taboos: &["Avoid alcohol during spiritual work"],
        prescriptions: &["Cleanse with shea butter and salt", "Keep a dream journal"],
        orisha: &["Ọ̀yá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Beginning",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 12, binary: 0b00001100,
        name: "Ẹ̀jì Ogbe / Òtúrá Méjì",
        archetype: "The Code-Walker",
        description: "This Odù opens gateways. Communication, pattern-recognition, and digital prophecy.",
        taboos: &["Avoid outdated thinking"],
        prescriptions: &["Speak into water then drink", "Offer kola nut to your Ifá tools"],
        orisha: &["Ọ̀rúnmìlà", "Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 13, binary: 0b00001101,
        name: "Ẹ̀jì Ogbe / Ìrẹtẹ̀ Méjì",
        archetype: "The Silent Builder",
        description: "Stubborn lessons demand humility and persistence. Irete within Ogbe builds sacred patience.",
        taboos: &["Avoid complaining"],
        prescriptions: &["Write a vow and bury it beneath earth", "Honor elders"],
        orisha: &["Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Seed Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 14, binary: 0b00001110,
        name: "Ẹ̀jì Ogbe / Òsé Méjì",
        archetype: "The Mirror of Delight",
        description: "Joy, beauty, and sweetness. Ọ̀ṣun's mirror blesses artistry, love, and sacred femininity.",
        taboos: &["Avoid bitter speech"],
        prescriptions: &["Offer honey and flowers", "Wear white and gold"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Origin",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 15, binary: 0b00001111,
        name: "Ẹ̀jì Ogbe / Òfún Méjì",
        archetype: "The Infinite Threshold",
        description: "The final mirror. Completion, vastness, and transcendence. The sage's breath before renewal.",
        taboos: &["Avoid unfinished rituals"],
        prescriptions: &["Complete all pending offerings", "Give thanks publicly"],
        orisha: &["Olódùmarè", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },
];
