//! WAVE 10 — Òsá Méjì / x  (indices 144–159)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 10 — Òsá Méjì / x  (indices 144–159)
    // Binary: 1001 xxxx  |  Opcode: Sub
    // ────────────────────────────────────────────────
    Odu { index: 144, binary: 0b10010000,
        name: "Òsá Méjì / Ẹ̀jì Ogbe",
        archetype: "The Thunder Herald",
        description: "Thunder announces beginnings. Clarity arrives through sudden light — bold initiation is called.",
        taboos: &["Avoid fearing sudden change"],
        prescriptions: &["Stand barefoot in a thunderstorm", "Call out your purpose during lightning"],
        orisha: &["Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Limit",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 145, binary: 0b10010001,
        name: "Òsá Méjì / Òyèkú Méjì",
        archetype: "The Shadow Storm",
        description: "Dark storm sky. Cleansing of shadow through fierce storms — rebirth follows.",
        taboos: &["Avoid hiding from your shadows"],
        prescriptions: &["Fast during stormy nights", "Meditate on rain's sound"],
        orisha: &["Ọ̀yá", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Silent Refusal",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 146, binary: 0b10010010,
        name: "Òsá Méjì / Ìwòrì Méjì",
        archetype: "The Flash Seer",
        description: "Reflections in lightning. Sudden insights spark awakening through flashes of understanding.",
        taboos: &["Avoid clinging to old beliefs"],
        prescriptions: &["Write down sudden ideas", "Practice breathwork after lightning strikes"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Watchful Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 147, binary: 0b10010011,
        name: "Òsá Méjì / Òdí Méjì",
        archetype: "The Calm Eye",
        description: "Stillness before storm. The silence that precedes great change and divine movement.",
        taboos: &["Avoid ignoring signs of pending change"],
        prescriptions: &["Sit in quiet before dawn", "Offer water and tobacco to altar"],
        orisha: &["Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Broken Loop Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 148, binary: 0b10010100,
        name: "Òsá Méjì / Ìròsùn Méjì",
        archetype: "The Flame Dancer",
        description: "Firestorm dance. Fire's passion merges with thunder's force — wild purge of spirit and matter.",
        taboos: &["Avoid suppressing intense emotions"],
        prescriptions: &["Dance with firelight", "Offer red palm oil to fire deity"],
        orisha: &["Ṣàngó", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Ledger Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 149, binary: 0b10010101,
        name: "Òsá Méjì / Òwónrín Méjì",
        archetype: "The Thunder Jester",
        description: "Trickster's thunder. Playful disruption and paradox shake fixed ideas with laughter and surprise.",
        taboos: &["Avoid taking everything too seriously"],
        prescriptions: &["Tell a joke in sacred space", "Practice laughter meditation"],
        orisha: &["Èṣù", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Unmasking Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 150, binary: 0b10010110,
        name: "Òsá Méjì / Òbàrà Méjì",
        archetype: "The Storm Orator",
        description: "Voice of the storm. Commands transformation through sacred speech vibrating with power.",
        taboos: &["Avoid idle chatter during storms"],
        prescriptions: &["Chant storm prayers", "Speak blessings into the wind"],
        orisha: &["Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Residue Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 151, binary: 0b10010111,
        name: "Òsá Méjì / Ọ̀kànràn Méjì",
        archetype: "The Lightning Cutter",
        description: "Lightning strikes disruption. Illusions cut, rapid transformation forced through shock.",
        taboos: &["Avoid clinging to illusions"],
        prescriptions: &["Visualize lightning cleansing your aura", "Break an old habit in ritual"],
        orisha: &["Ṣàngó", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Execution Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 152, binary: 0b10011000,
        name: "Òsá Méjì / Ògúndá Méjì",
        archetype: "The Thunder Forger",
        description: "Storm clears the path. Sacred force clears obstacles with thunderous power and precision.",
        taboos: &["Avoid hesitating in moments of opportunity"],
        prescriptions: &["Use a machete to clear brush in ritual", "Offer iron tools to Ògún"],
        orisha: &["Ṣàngó", "Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Restraint",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 153, binary: 0b10011001,
        name: "Òsá Méjì / Òsá Méjì",
        archetype: "The Divine Storm",
        description: "Pure storm essence. Raw divine power — the unfiltered voice of the sky breaking through.",
        taboos: &["Avoid disrespecting natural forces"],
        prescriptions: &["Meditate during a thunderstorm", "Offer palm nuts to Òsà"],
        orisha: &["Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 154, binary: 0b10011010,
        name: "Òsá Méjì / Ìkà Méjì",
        archetype: "The Storm Purifier",
        description: "Venomous thunder. Purges through confrontation and fierce cleansing — shock therapy for the soul.",
        taboos: &["Avoid passive resistance to change"],
        prescriptions: &["Drink bitter herbs during storm", "Confront what you fear with honesty"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Consent Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 155, binary: 0b10011011,
        name: "Òsá Méjì / Òtúrúpòn Méjì",
        archetype: "The Storm Catalyst",
        description: "Chaotic storm. Wild energy unbound — madness, inspiration, and divine chaos unleashed.",
        taboos: &["Avoid suppressing creative chaos"],
        prescriptions: &["Write spontaneously during storms", "Create abstract art in ritual"],
        orisha: &["Ọ̀yá", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Vision Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 156, binary: 0b10011100,
        name: "Òsá Méjì / Òtúrá Méjì",
        archetype: "The Storm Architect",
        description: "Order in chaos. Storm's wildness channels into structured creation and sacred form.",
        taboos: &["Avoid rigid control over natural flow"],
        prescriptions: &["Draw sacred geometry in sand", "Build wind chimes to harness storms"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Growth Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 157, binary: 0b10011101,
        name: "Òsá Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Thunder Judge",
        description: "Judgment in the storm. Divine justice delivered with thunder's authority, shaking corrupt foundations.",
        taboos: &["Avoid evading responsibility"],
        prescriptions: &["Call out injustices during storms", "Write petitions on palm leaves"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 158, binary: 0b10011110,
        name: "Òsá Méjì / Òsé Méjì",
        archetype: "The Storm Lover",
        description: "Pleasure in tempest. Ecstatic release blends with wild storms — healing through passionate chaos.",
        taboos: &["Avoid denying emotional release"],
        prescriptions: &["Dance freely in the rain", "Offer sweet libations to Òsà"],
        orisha: &["Ọ̀ṣun", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Brake",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },

    Odu { index: 159, binary: 0b10011111,
        name: "Òsá Méjì / Òfún Méjì",
        archetype: "The Storm Bringer",
        description: "Light after storm. Renewal and clarity born from upheaval — the dawn of new consciousness.",
        taboos: &["Avoid clinging to past storms"],
        prescriptions: &["Meditate at sunrise post-storm", "Offer white flowers to Òsà"],
        orisha: &["Ọ̀yá", "Olódùmarè"],
        interpretation_type: "synthetic",
        universal_name: "The Measured Silence",
        vessel: ActionVessel::Restraint,
        opcode: OduOpCode::Sub },
];
