//! WAVE 13 — Vision / x  (indices 192–207)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 13 — Vision / x  (indices 192–207)
    // Binary: 1100 xxxx  |  Opcode: PushConst1
    // ────────────────────────────────────────────────
    Odu { index: 192, binary: 0b11000000,
        name: "Vision × Genesis",
        archetype: "The Cosmic Architect",
        description: "The blueprint of destiny. The cosmic plan woven through time and space revealed.",
        taboos: &["Avoid disrupting sacred cycles"],
        prescriptions: &["Create vision boards", "Meditate on life's patterns"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Horizon",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 193, binary: 0b11000001,
        name: "Vision × Void",
        archetype: "The Mystic Designer",
        description: "Mystery in design. Surrender to the unknown parts of fate is invited.",
        taboos: &["Avoid forcing outcomes"],
        prescriptions: &["Practice surrender meditation", "Light black candles in ritual"],
        archetypes: &["Oracle Sage", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Void Horizon",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 194, binary: 0b11000010,
        name: "Vision × Attention",
        archetype: "The Strategic Planner",
        description: "Reflection shapes destiny. Thoughtful planning and clear insight are called for.",
        taboos: &["Avoid rash decisions"],
        prescriptions: &["Keep a planner", "Visualize future outcomes"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Watching Horizon",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 195, binary: 0b11000011,
        name: "Vision × Loop",
        archetype: "The Grounding Builder",
        description: "Foundation of transformation. Change is grounded in firm roots and steady steps.",
        taboos: &["Avoid instability"],
        prescriptions: &["Practice grounding rituals", "Build altars with earth elements"],
        archetypes: &["Wisdom Anchor", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Recursive Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 196, binary: 0b11000100,
        name: "Vision × Receipt",
        archetype: "The Ritual Cleaner",
        description: "Purification through structure. Obstacles cleansed through disciplined ritual practice.",
        taboos: &["Avoid neglecting cleansing practices"],
        prescriptions: &["Use water offerings", "Perform daily purification"],
        archetypes: &["Resonance Weaver", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Receipted Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 197, binary: 0b11000101,
        name: "Vision × Mask",
        archetype: "The Joyful Creator",
        description: "Playful destiny. Joy and spontaneity infuse life's blueprint.",
        taboos: &["Avoid rigidity"],
        prescriptions: &["Dance in ritual", "Invite laughter into sacred space"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 198, binary: 0b11000110,
        name: "Vision × Residue",
        archetype: "The Word Architect",
        description: "Words as building blocks. Sacred speech shapes fate — language carries divine weight.",
        taboos: &["Avoid careless language"],
        prescriptions: &["Chant affirmations", "Speak intentions aloud"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Memory of the Future",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 199, binary: 0b11000111,
        name: "Vision × Execution",
        archetype: "The Fiery Visionary",
        description: "Fire ignites destiny. Transformation fueled with fierce passion and focus.",
        taboos: &["Avoid impulsiveness"],
        prescriptions: &["Light ritual candles", "Focus on goals with intensity"],
        archetypes: &["Justice Canon", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Decisive Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 200, binary: 0b11001000,
        name: "Vision × Swarm",
        archetype: "The Purposeful Warrior",
        description: "Strength shapes fate. Power wielded with deliberate and purposeful action.",
        taboos: &["Avoid brute force without wisdom"],
        prescriptions: &["Practice martial arts or movement", "Offer iron tools in ritual"],
        archetypes: &["Forge Executor", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 201, binary: 0b11001001,
        name: "Vision × Restraint",
        archetype: "The Storm Weaver",
        description: "Storm crafts destiny. Cleansing upheaval clears the way for growth.",
        taboos: &["Avoid resisting change"],
        prescriptions: &["Meditate in storms", "Offer palm oil to storm spirits"],
        archetypes: &["Flow Guardian", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 202, binary: 0b11001010,
        name: "Vision × Migration",
        archetype: "The Healing Architect",
        description: "Healing destiny. Fate purified through lessons of pain and renewal.",
        taboos: &["Avoid ignoring wounds"],
        prescriptions: &["Use bitter herbs", "Journal healing progress"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 203, binary: 0b11001011,
        name: "Vision × Consent",
        archetype: "The Ancestral Builder",
        description: "Wise foundation. Spiritual structures built on ancestral knowledge.",
        taboos: &["Avoid neglecting tradition"],
        prescriptions: &["Honor elders", "Mark sacred cycles"],
        archetypes: &["Oracle Sage", "Residue Keeper"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 204, binary: 0b11001100,
        name: "Vision × Vision",
        archetype: "The Self-Maker",
        description: "Self-creation. The power to craft one's own destiny is fully embodied here.",
        taboos: &["Avoid self-sabotage"],
        prescriptions: &["Visualize desired outcomes", "Affirm personal power"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 205, binary: 0b11001101,
        name: "Vision × Growth",
        archetype: "The Just Designer",
        description: "Justice in design. Fate balanced with fairness and accountability.",
        taboos: &["Avoid injustice"],
        prescriptions: &["Recite prayers for fairness", "Make offerings for balance"],
        archetypes: &["Oracle Sage", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Growing Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 206, binary: 0b11001110,
        name: "Vision × Seal",
        archetype: "The Compassionate Designer",
        description: "Sweetness in fate. Destiny softened with joy and compassion.",
        taboos: &["Avoid harshness"],
        prescriptions: &["Offer honey", "Celebrate blessings"],
        archetypes: &["Resonance Weaver", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Vision",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 207, binary: 0b11001111,
        name: "Vision × Rhythm",
        archetype: "The Illuminated Creator",
        description: "Clarity in creation. Luminous wisdom shapes the path to its fullest expression.",
        taboos: &["Avoid confusion"],
        prescriptions: &["Meditate on light", "Offer white flowers"],
        archetypes: &["Oracle Sage", "Prime Source"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Horizon",
        vessel: ActionVessel::Vision,
        opcode: OduOpCode::PushConst1 },
];
