//! WAVE 9 — Ògúndá Méjì / x  (indices 128–143)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 9 — Ògúndá Méjì / x  (indices 128–143)
    // Binary: 1000 xxxx  |  Opcode: CastCowries
    // ────────────────────────────────────────────────
    Odu { index: 128, binary: 0b10000000,
        name: "Ògúndá Méjì / Ẹ̀jì Ogbe",
        archetype: "The Sacred Forger",
        description: "Path opens with tools. Breakthrough by building — divine progress through sacred force.",
        taboos: &["Avoid procrastination when momentum builds"],
        prescriptions: &["Forge a path in nature", "Bless your tools with palm oil"],
        orisha: &["Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 129, binary: 0b10000001,
        name: "Ògúndá Méjì / Òyèkú Méjì",
        archetype: "The Grave Opener",
        description: "The blade pierces the void. Motion to stagnation — shaking loose what is hidden or buried.",
        taboos: &["Avoid digging into old pain without intention"],
        prescriptions: &["Strike earth three times before sleep", "Offer iron to the ancestors"],
        orisha: &["Ògún", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Void Chorus",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 130, binary: 0b10000010,
        name: "Ògúndá Méjì / Ìwòrì Méjì",
        archetype: "The Vision Smith",
        description: "Reflection becomes action. Translating visions into deeds — forging dreams in the fire of will.",
        taboos: &["Avoid dreaming without doing"],
        prescriptions: &["Write your vision and act on one step within 24 hours", "Anoint your feet with ash"],
        orisha: &["Ògún", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Watching Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 131, binary: 0b10000011,
        name: "Ògúndá Méjì / Òdí Méjì",
        archetype: "The Rooted Warrior",
        description: "Stillness births the blade. Inner silence meets outer precision — motion forged from womb-space.",
        taboos: &["Avoid rushing when you have not rooted"],
        prescriptions: &["Sit in silence until a decision arises", "Pour water slowly over a blade"],
        orisha: &["Ògún", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Feedback Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 132, binary: 0b10000100,
        name: "Ògúndá Méjì / Ìròsùn Méjì",
        archetype: "The Firebound Smith",
        description: "The fire sharpens. Trial by heat — tension, conflict, and sacred struggle refine your edge.",
        taboos: &["Avoid avoiding hard conversations"],
        prescriptions: &["Sharpen a blade in ritual", "Fast on the day of Mars"],
        orisha: &["Ògún", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Joint Receipt",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 133, binary: 0b10000101,
        name: "Ògúndá Méjì / Òwónrín Méjì",
        archetype: "The Iron Trickster",
        description: "Trickster tempers the sword. Intent tested through misdirection — clarity forced in movement.",
        taboos: &["Avoid quick action without discernment"],
        prescriptions: &["Tie red thread around your dominant hand", "Meditate with a metal object"],
        orisha: &["Ògún", "Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 134, binary: 0b10000110,
        name: "Ògúndá Méjì / Òbàrà Méjì",
        archetype: "The Commanding Blade",
        description: "Speech ignites motion. Voice as a tool of transformation — command creates momentum.",
        taboos: &["Avoid speaking aimlessly"],
        prescriptions: &["Declare your next move aloud daily", "Whistle while walking your ritual path"],
        orisha: &["Ògún", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Memory Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 135, binary: 0b10000111,
        name: "Ògúndá Méjì / Ọ̀kànràn Méjì",
        archetype: "The Revolutionary Smith",
        description: "Blade meets fire. Revolution in motion — upheaval, breakage, and divine pressure to evolve.",
        taboos: &["Avoid fighting change with old tactics"],
        prescriptions: &["Break something obsolete in ritual", "Offer red cloth to Ògún"],
        orisha: &["Ògún", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Iron Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 136, binary: 0b10001000,
        name: "Ògúndá Méjì / Ògúndá Méjì",
        archetype: "The Iron Pillar",
        description: "Steel within steel. Pure willpower — unshakable drive, clear purpose, force guided by discipline.",
        taboos: &["Avoid hesitation once the path is chosen"],
        prescriptions: &["Train your body in rhythm", "Forge a ritual blade with your name on it"],
        orisha: &["Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 137, binary: 0b10001001,
        name: "Ògúndá Méjì / Òsá Méjì",
        archetype: "The Storm Cutter",
        description: "Blade in the storm. Chaotic transformation — sudden cuts, dramatic shifts, divine thunder.",
        taboos: &["Avoid fearing the unknown"],
        prescriptions: &["Dance in rain or thunder", "Speak to iron in your native tongue"],
        orisha: &["Ògún", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Dissenting Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 138, binary: 0b10001010,
        name: "Ògúndá Méjì / Ìkà Méjì",
        archetype: "The Curse Breaker",
        description: "Cutting cords of poison. Purges spiritual toxins — protection from curses, envy, psychic attack.",
        taboos: &["Avoid tolerating spiritual decay"],
        prescriptions: &["Cleanse with iron filings and salt", "Bury a blade under your bed for three nights"],
        orisha: &["Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 139, binary: 0b10001011,
        name: "Ògúndá Méjì / Òtúrúpòn Méjì",
        archetype: "The Wild Forger",
        description: "Mad blade, sacred edge. Dances with chaos to find creation — wildness as divine forge.",
        taboos: &["Avoid suppressing your wild urges"],
        prescriptions: &["Create something with your hands", "Channel anger into movement"],
        orisha: &["Ògún", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Consensual Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 140, binary: 0b10001100,
        name: "Ògúndá Méjì / Òtúrá Méjì",
        archetype: "The Divine Engineer",
        description: "The architect's sword. Vision into matter — building with precision and protective power.",
        taboos: &["Avoid building without a blueprint"],
        prescriptions: &["Draw sacred geometries in ash", "Hammer something while chanting your goal"],
        orisha: &["Ògún", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Visionary Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 141, binary: 0b10001101,
        name: "Ògúndá Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Warrior Judge",
        description: "Sword of justice. Defends truth and punishes corruption — righteous fury with ancestral backing.",
        taboos: &["Avoid silence in the face of injustice"],
        prescriptions: &["Recite ancestral names before battle", "Write your truth in red ink"],
        orisha: &["Ògún", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Growing Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 142, binary: 0b10001110,
        name: "Ògúndá Méjì / Òsé Méjì",
        archetype: "The Harmonized Warrior",
        description: "Iron and sweetness. Force blends with grace — strategic motion guided by beauty and balance.",
        taboos: &["Avoid choosing between softness and strength"],
        prescriptions: &["Oil a blade with honey in ritual", "Make peace after battle — symbolic or real"],
        orisha: &["Ògún", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Swarm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },

    Odu { index: 143, binary: 0b10001111,
        name: "Ògúndá Méjì / Òfún Méjì",
        archetype: "The Eternal Blade",
        description: "Steel of the divine. Mission aligns with cosmic order — action that echoes through eternity.",
        taboos: &["Avoid acting without soul alignment"],
        prescriptions: &["Speak your vow to the sky before sunrise", "Make an offering at a crossroads"],
        orisha: &["Ògún", "Olódùmarè"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Storm",
        vessel: ActionVessel::Swarm,
        opcode: OduOpCode::CastCowries },
];
