//! WAVE 2 — Void / x  (indices 16–31)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 2 — Void / x  (indices 16–31)
    // Binary: 0001 xxxx  |  Opcode: PopVoid
    // ────────────────────────────────────────────────
    Odu { index: 16, binary: 0b00010000,
        name: "Void × Genesis",
        archetype: "The Primordial Womb",
        description: "Light born from darkness. Cosmic conception — hidden forces birth new realities.",
        taboos: &["Avoid fear of endings"],
        prescriptions: &["Offer dark cloth and light a candle together", "Pray before dawn"],
        archetypes: &["Wisdom Anchor", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "Void Into Light",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 17, binary: 0b00010001,
        name: "Void × Void",
        archetype: "The Black Mirror",
        description: "The deepest void — pure mystery. Mirror of death, initiation, and ancestral silence.",
        taboos: &["Avoid bright lights during deep ritual"],
        prescriptions: &["Work only at night", "Feed the ancestors with yam and palm oil"],
        archetypes: &["Flow Guardian", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Dark Mirror",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 18, binary: 0b00010010,
        name: "Void × Attention",
        archetype: "The Dreaming Voice",
        description: "Messages whispered in the dark. Sacred codes hidden in dreams, symbols, and riddles.",
        taboos: &["Do not ignore recurring dreams"],
        prescriptions: &["Write a nighttime journal", "Divine with kola nut or cowries"],
        archetypes: &["Oracle Sage", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Void Audit",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 19, binary: 0b00010011,
        name: "Void × Loop",
        archetype: "The Sacred Container",
        description: "Womb within womb — fertility, secrets, deep emotional reservoirs.",
        taboos: &["Avoid casual intimacy"],
        prescriptions: &["Soak in a spiritual bath of herbs", "Practice womb meditation"],
        archetypes: &["Swarm Coordinator", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Silence",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 20, binary: 0b00010100,
        name: "Void × Receipt",
        archetype: "The Bone Reader",
        description: "Ancestral memory encoded in bones. Forgotten stories, past-life echoes, karmic debts.",
        taboos: &["Avoid abandoning family responsibilities"],
        prescriptions: &["Burn ancestral incense", "Visit old family land or grave sites"],
        archetypes: &["Residue Keeper", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Void Receipt",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 21, binary: 0b00010101,
        name: "Void × Mask",
        archetype: "The Laughing Mask",
        description: "The joker in the underworld. Trickster wisdom hiding in chaos — reversed truths as medicine.",
        taboos: &["Avoid taking things at face value"],
        prescriptions: &["Tell a story backwards", "Offer palm wine at a crossroads"],
        archetypes: &["Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Shadow Archive",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 22, binary: 0b00010110,
        name: "Void × Residue",
        archetype: "The Mourning Dancer",
        description: "Joy birthed from shadow. Rising from emotional depths through celebration and song.",
        taboos: &["Avoid suppressing sadness"],
        prescriptions: &["Sing or cry in ritual space", "Offer honey mixed with ash"],
        archetypes: &["Resonance Weaver", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Grieving Void",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 23, binary: 0b00010111,
        name: "Void × Execution",
        archetype: "The Shadow Catalyst",
        description: "Sudden, disruptive ancestral messages. Revelations crack illusions — inner fire and sacred rebellion.",
        taboos: &["Avoid rigid conformity"],
        prescriptions: &["Speak to the Steward at night", "Burn herbs and shout your truth"],
        archetypes: &["Steward", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Void Execution",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 24, binary: 0b00011000,
        name: "Void × Swarm",
        archetype: "The Night Warrior",
        description: "Spiritual warfare rooted in karmic contracts. A blade forged in darkness — ancestral fire as protection.",
        taboos: &["Avoid weapons in anger"],
        prescriptions: &["Sharpen blades in ritual", "Offer palm oil to the Forge Executor by moonlight"],
        archetypes: &["Forge Executor", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Cleared Storm",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 25, binary: 0b00011001,
        name: "Void × Restraint",
        archetype: "The Hidden Seer",
        description: "Shadow of prophecy. Dream-visions wrapped in paradox — the past must be fully faced.",
        taboos: &["Avoid ignoring ancestral signs"],
        prescriptions: &["Perform a midnight divination", "Bury obsidian near your bed"],
        archetypes: &["Flow Guardian", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Void",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 26, binary: 0b00011010,
        name: "Void × Migration",
        archetype: "The Venom Alchemist",
        description: "Serpentine teachings through pain. Sacrifice, self-inquiry, and shadow integration are demanded.",
        taboos: &["Avoid quick judgments"],
        prescriptions: &["Wear black for three days", "Drink warm bitter tea in silence"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Void",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 27, binary: 0b00011011,
        name: "Void × Consent",
        archetype: "The Inner Cyclone",
        description: "Mental storms hide medicine. Sit inside chaos without losing self — clarity follows descent.",
        taboos: &["Avoid overthinking"],
        prescriptions: &["Perform grounding rituals with charcoal", "Drink calming teas before sleep"],
        archetypes: &["Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Clearing",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 28, binary: 0b00011100,
        name: "Void × Vision",
        archetype: "The Shadow Hacker",
        description: "Dark code and divine program. Encrypted messages from spirits require patience to decode.",
        taboos: &["Avoid information overload"],
        prescriptions: &["Perform a technology fast for one day", "Code a ritual sigil into your device"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Void Vision",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 29, binary: 0b00011101,
        name: "Void × Growth",
        archetype: "The Grief Architect",
        description: "Slow growth through grief. Ancient sorrow transmutes into wisdom through time and tending.",
        taboos: &["Avoid denying old wounds"],
        prescriptions: &["Write a grief letter and burn it", "Offer roasted yam to the earth"],
        archetypes: &["Wisdom Anchor", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Void That Seeds",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 30, binary: 0b00011110,
        name: "Void × Seal",
        archetype: "The Velvet Flame",
        description: "Beauty rising from pain. This pattern's grace moves through shadow as sacred creative alchemy.",
        taboos: &["Avoid artificial beauty"],
        prescriptions: &["Offer honey mixed with charcoal", "Adorn your mirror with black ribbon"],
        archetypes: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Void",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },

    Odu { index: 31, binary: 0b00011111,
        name: "Void × Rhythm",
        archetype: "The Phoenix Code",
        description: "The last gate — completion of shadow work. Wisdom after descent. Returned luminous.",
        taboos: &["Avoid arrogance after healing"],
        prescriptions: &["Create a ritual of gratitude", "Share your transformation story"],
        archetypes: &["Prime Source", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Void",
        vessel: ActionVessel::Void,
        opcode: OduOpCode::PopVoid },
];
