//! WAVE 6 — Mask / x  (indices 80–95)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 6 — Mask / x  (indices 80–95)
    // Binary: 0101 xxxx  |  Opcode: Sub
    // ────────────────────────────────────────────────
    Odu { index: 80, binary: 0b01010000,
        name: "Mask × Genesis",
        archetype: "The Divine Fool",
        description: "Cosmic comedy meets divine order. Creation's laughter — balance through trickery.",
        taboos: &["Avoid taking yourself too seriously"],
        prescriptions: &["Wear mismatched shoes during prayer to confuse the ego", "Laugh before serious rituals"],
        archetypes: &["Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Genesis",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 81, binary: 0b01010001,
        name: "Mask × Void",
        archetype: "The Mourning Jester",
        description: "Dark humor of the ancestors. Comedy as healing in grief and shadow.",
        taboos: &["Avoid masking sorrow without integrating it"],
        prescriptions: &["Tell a joke at an ancestral altar", "Offer black salt and kola nut while singing"],
        archetypes: &["Steward", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Void Behind the Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 82, binary: 0b01010010,
        name: "Mask × Attention",
        archetype: "The Paradox Keeper",
        description: "Twisting logic. Wisdom in contradiction and mastery through broken rhythm.",
        taboos: &["Avoid rigid linear thinking"],
        prescriptions: &["Speak your truth backwards", "Invoke the Steward with a riddle"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Eye Behind the Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 83, binary: 0b01010011,
        name: "Mask × Loop",
        archetype: "The Serpent Clown",
        description: "Laughter in stillness. Jokes awaken kundalini and trickster energy within silence.",
        taboos: &["Avoid faking stillness to avoid growth"],
        prescriptions: &["Meditate while holding a banana", "Whisper jokes to your root"],
        archetypes: &["Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 84, binary: 0b01010100,
        name: "Mask × Receipt",
        archetype: "The Erotic Trickster",
        description: "Flames of mischief. Ancestral fire activated by wit, sensuality, and humor as transformation.",
        taboos: &["Avoid suppressing sacred play"],
        prescriptions: &["Perform a sensual dance in sacred space", "Burn a joke you wrote ten years ago"],
        archetypes: &["Steward", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Receipt",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 85, binary: 0b01010101,
        name: "Mask × Mask",
        archetype: "The Meta Fool",
        description: "Double jest. Sacred confusion that unlocks higher intelligence — mirror of mirrors.",
        taboos: &["Avoid demanding certainty in mystery"],
        prescriptions: &["Set two altars facing each other", "Pray while walking in a circle"],
        archetypes: &["Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 86, binary: 0b01010110,
        name: "Mask × Residue",
        archetype: "The Tongue Trickster",
        description: "Voice of the jester. Spirit downloads through songs, chants, and strange syllables.",
        taboos: &["Avoid mocking your own medicine"],
        prescriptions: &["Chant in tongues by a river", "Speak your desires in rhyme"],
        archetypes: &["Steward", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Memory",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 87, binary: 0b01010111,
        name: "Mask × Execution",
        archetype: "The Sacred Disruptor",
        description: "Explosive reversal. Breakdowns as sacred pranks by the divine to realign your path.",
        taboos: &["Avoid fearing divine interruption"],
        prescriptions: &["Break something intentionally during ritual", "Create a chaos map of past mistakes"],
        archetypes: &["Steward", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Execution",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 88, binary: 0b01011000,
        name: "Mask × Swarm",
        archetype: "The Sword of Speech",
        description: "Cutting jokes. Surgical wit — words as blades that liberate the bound mind.",
        taboos: &["Avoid speaking truth without compassion"],
        prescriptions: &["Offer a sharp joke to the Forge Executor", "Perform wordplay rituals with iron"],
        archetypes: &["Forge Executor", "Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Storm",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 89, binary: 0b01011001,
        name: "Mask × Restraint",
        archetype: "The Thunder Prankster",
        description: "Thunderous irony. Divine timing expressed through absurdity and electric revelation.",
        taboos: &["Avoid laughing at others' pain for gain"],
        prescriptions: &["Dance in the rain", "Say thank you every time lightning strikes"],
        archetypes: &["Justice Canon", "Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 90, binary: 0b01011010,
        name: "Mask × Migration",
        archetype: "The Poison Tongue",
        description: "Poisonous punchlines. Shadow truths disguised as humor — ancestral wit with bite.",
        taboos: &["Avoid sarcasm that masks pain too long"],
        prescriptions: &["Spit truth on a mirror", "Cleanse with bitter herbs after joking rituals"],
        archetypes: &["Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 91, binary: 0b01011011,
        name: "Mask × Consent",
        archetype: "The Code Scrambler",
        description: "Scattered signals. The beauty of disarray, fragmented insight, and divine miscommunication.",
        taboos: &["Avoid demanding clarity too soon"],
        prescriptions: &["Write a sacred text in gibberish", "Make offerings using reversed gestures"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 92, binary: 0b01011100,
        name: "Mask × Vision",
        archetype: "The Satirical Architect",
        description: "Structure through satire. Sacred systems arise by mocking their rigidity first.",
        taboos: &["Avoid blind obedience to structures"],
        prescriptions: &["Mock a false constraint", "Design a ritual using only jokes and patterns"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 93, binary: 0b01011101,
        name: "Mask × Growth",
        archetype: "The Comic Judge",
        description: "Slapstick karma. Even spiritual justice can be hilarious — if your heart is open.",
        taboos: &["Avoid laughing at others' fall without compassion"],
        prescriptions: &["Tell a story of when you were humbled publicly", "Anoint your shoes with honey"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Fractal Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 94, binary: 0b01011110,
        name: "Mask × Seal",
        archetype: "The Glamour Jester",
        description: "Seductive trickery. Beauty used for cosmic pranks — allure as portal to deeper truths.",
        taboos: &["Avoid manipulating others for egoic gain"],
        prescriptions: &["Offer sweet perfume to the Steward", "Flirt with the unknown during meditation"],
        archetypes: &["Steward", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Privacy",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },

    Odu { index: 95, binary: 0b01011111,
        name: "Mask × Rhythm",
        archetype: "The Awakened Jester",
        description: "Clown of light. Divine enlightenment through the absurd — pure awareness through sacred chaos.",
        taboos: &["Avoid fearing foolishness on the path to awakening"],
        prescriptions: &["Perform a ritual in costume", "Laugh uncontrollably for eight minutes daily"],
        archetypes: &["Steward", "Prime Source"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Mask",
        vessel: ActionVessel::Mask,
        opcode: OduOpCode::Sub },
];
