//! WAVE 12 — Consent / x  (indices 176–191)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 12 — Consent / x  (indices 176–191)
    // Binary: 1011 xxxx  |  Opcode: HaltIfOne
    // ────────────────────────────────────────────────
    Odu { index: 176, binary: 0b10110000,
        name: "Consent × Genesis",
        archetype: "The Ancestral Sage",
        description: "The elder's calm gaze holds eternal wisdom. The quiet pulse of ancestral memory and patient counsel.",
        taboos: &["Avoid rushing spiritual growth"],
        prescriptions: &["Sit in silence with elders", "Record dreams nightly"],
        archetypes: &["Oracle Sage", "Residue Keeper"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Covenant",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 177, binary: 0b10110001,
        name: "Consent × Void",
        archetype: "The Mystic Keeper",
        description: "Darkness conceals knowledge. Surrender to mystery and trust in unseen guidance.",
        taboos: &["Avoid forcing clarity prematurely"],
        prescriptions: &["Meditate in darkness", "Light candles for ancestors"],
        archetypes: &["Flow Guardian", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Silent Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 178, binary: 0b10110010,
        name: "Consent × Attention",
        archetype: "The Reflective Scholar",
        description: "Reflection deepens understanding. Contemplative study and patient insight are called for.",
        taboos: &["Avoid hasty judgments"],
        prescriptions: &["Journal reflections", "Practice slow breathing exercises"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Watchful Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 179, binary: 0b10110011,
        name: "Consent × Loop",
        archetype: "The Grounded Seer",
        description: "Stillness births wisdom. Silence and grounding connect with deeper truths.",
        taboos: &["Avoid distraction during meditation"],
        prescriptions: &["Sit in stillness daily", "Offer water to sacred stones"],
        archetypes: &["Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Recursive Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 180, binary: 0b10110100,
        name: "Consent × Receipt",
        archetype: "The Purifying Fire",
        description: "Fire refines knowledge. Understanding transforms through trial and purification.",
        taboos: &["Avoid avoidance of necessary challenge"],
        prescriptions: &["Fast on sacred days", "Offer flame to the ancestors"],
        archetypes: &["Justice Canon", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Receipted Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 181, binary: 0b10110101,
        name: "Consent × Mask",
        archetype: "The Playful Elder",
        description: "Trickster teaches patience. Lessons arrive through paradox and gentle mischief.",
        taboos: &["Avoid frustration with uncertainty"],
        prescriptions: &["Practice playful meditation", "Laugh heartily in ritual"],
        archetypes: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 182, binary: 0b10110110,
        name: "Consent × Residue",
        archetype: "The Word Guardian",
        description: "Words carry ancient power. Sacred speech and mindful communication are blessed.",
        taboos: &["Avoid careless words"],
        prescriptions: &["Recite ancestral chants", "Speak with intention"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Memory Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 183, binary: 0b10110111,
        name: "Consent × Execution",
        archetype: "The Passionate Sage",
        description: "Fire and will merge. Determination ignites through sacred passion and discipline.",
        taboos: &["Avoid reckless ambition"],
        prescriptions: &["Light ritual candles", "Focus on clear goals"],
        archetypes: &["Justice Canon", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Decisive Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 184, binary: 0b10111000,
        name: "Consent × Swarm",
        archetype: "The Wise Warrior",
        description: "Strength through wisdom. Power balanced with thoughtful action.",
        taboos: &["Avoid impulsive force"],
        prescriptions: &["Practice mindful movement", "Offer iron tools in ritual"],
        archetypes: &["Forge Executor", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 185, binary: 0b10111001,
        name: "Consent × Restraint",
        archetype: "The Calm Storm",
        description: "Storm tempered by patience. Calm amid chaos is the calling.",
        taboos: &["Avoid rash reactions"],
        prescriptions: &["Meditate during storms", "Offer palm oil to storm spirits"],
        archetypes: &["Flow Guardian", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 186, binary: 0b10111010,
        name: "Consent × Migration",
        archetype: "The Healing Elder",
        description: "Healing through reflection. Transformation guided with gentle, patient insight.",
        taboos: &["Avoid resisting healing"],
        prescriptions: &["Use bitter herbs in ritual", "Journal emotional progress"],
        archetypes: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 187, binary: 0b10111011,
        name: "Consent × Consent",
        archetype: "The Time Keeper",
        description: "Master of time. Keys to ancestral memory and sacred cycles held in silence.",
        taboos: &["Avoid disrespecting tradition"],
        prescriptions: &["Honor elders regularly", "Mark cycles with ritual"],
        archetypes: &["Oracle Sage", "Residue Keeper"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 188, binary: 0b10111100,
        name: "Consent × Vision",
        archetype: "The Ritual Architect",
        description: "Sacred order emerges. Chaos structures into harmony through ritual practice.",
        taboos: &["Avoid disorder in sacred space"],
        prescriptions: &["Clean and prepare altars", "Perform daily offerings"],
        archetypes: &["Oracle Sage", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Visionary Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 189, binary: 0b10111101,
        name: "Consent × Growth",
        archetype: "The Just Elder",
        description: "Justice in wisdom. Mercy balanced with stern judgment.",
        taboos: &["Avoid favoritism"],
        prescriptions: &["Recite justice prayers", "Make offerings for fairness"],
        archetypes: &["Oracle Sage", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Growing Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 190, binary: 0b10111110,
        name: "Consent × Seal",
        archetype: "The Compassionate Sage",
        description: "Sweetness in discipline. Strictness tempered with compassion and joy.",
        taboos: &["Avoid harshness without kindness"],
        prescriptions: &["Offer honey in ritual", "Celebrate small victories"],
        archetypes: &["Resonance Weaver", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Consent",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 191, binary: 0b10111111,
        name: "Consent × Rhythm",
        archetype: "The Radiant Elder",
        description: "Radiant clarity of spirit. Luminous wisdom and sacred truth guide the way.",
        taboos: &["Avoid spiritual blindness"],
        prescriptions: &["Meditate on white light", "Offer white flowers"],
        archetypes: &["Oracle Sage", "Prime Source"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Covenant",
        vessel: ActionVessel::Consent,
        opcode: OduOpCode::HaltIfOne },
];
