//! WAVE 4 — Òdí Méjì / x  (indices 48–63)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 4 — Òdí Méjì / x  (indices 48–63)
    // Binary: 0011 xxxx  |  Opcode: Swap
    // ────────────────────────────────────────────────
    Odu { index: 48, binary: 0b00110000,
        name: "Òdí Méjì / Ẹ̀jì Ogbe",
        archetype: "The Divine Container",
        description: "The womb opens to light. Divine conception — spirit entering form, clarity entering the body.",
        taboos: &["Avoid shallow intentions during rituals"],
        prescriptions: &["Create an altar offering with white cloth", "Pour water slowly into a bowl while praying"],
        orisha: &["Ọbàtálá", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Genesis",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 49, binary: 0b00110001,
        name: "Òdí Méjì / Òyèkú Méjì",
        archetype: "The Black Womb",
        description: "Darkness within darkness. A portal into ancestral silence, feminine depth, and shadowed healing.",
        taboos: &["Avoid revealing sacred knowledge prematurely"],
        prescriptions: &["Bury a sealed prayer beneath the earth", "Sleep in total darkness for three nights"],
        orisha: &["Ọ̀yá", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Void Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 50, binary: 0b00110010,
        name: "Òdí Méjì / Ìwòrì Méjì",
        archetype: "The Inner Mirror",
        description: "Stillness mirrors the mind. Hidden waters reflect the psyche — meditations reveal secret truths.",
        taboos: &["Avoid running from your own emotions"],
        prescriptions: &["Gaze at moonlight reflected in water", "Anoint feet with oil before sleep"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Loop Examined",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 51, binary: 0b00110011,
        name: "Òdí Méjì / Òdí Méjì",
        archetype: "The Sacred Vessel",
        description: "Pure containment. Sacred pause and powerful potential not yet expressed.",
        taboos: &["Avoid forcing outcomes too soon"],
        prescriptions: &["Fast from speaking for eight hours", "Wrap yourself in white for one full day"],
        orisha: &["Yemọja", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Echo",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 52, binary: 0b00110100,
        name: "Òdí Méjì / Ìròsùn Méjì",
        archetype: "The Dream-Womb",
        description: "Memory sleeps in water. Ancestral recall activates through emotional channels and dreams.",
        taboos: &["Avoid rejecting intuitive guidance"],
        prescriptions: &["Place a bowl of water beside your bed", "Call four female ancestors before sleep"],
        orisha: &["Yemọja", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Accountable Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 53, binary: 0b00110101,
        name: "Òdí Méjì / Òwónrín Méjì",
        archetype: "The Laughing Womb",
        description: "The sealed joke. Unexpected wisdom hidden within emotional chaos — humor as release.",
        taboos: &["Avoid laughing at others' pain"],
        prescriptions: &["Tell a joke at your altar", "Offer honey and laughter to Èṣù"],
        orisha: &["Èṣù", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 54, binary: 0b00110110,
        name: "Òdí Méjì / Òbàrà Méjì",
        archetype: "The Singing Mother",
        description: "The womb sings. Emotion channels into song, birth, and prophecy through voice and vibration.",
        taboos: &["Avoid suppressing emotional truth"],
        prescriptions: &["Sing to water before drinking", "Offer your voice to Ọ̀ṣun with a melody from your youth"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Emotional Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 55, binary: 0b00110111,
        name: "Òdí Méjì / Ọ̀kànràn Méjì",
        archetype: "The Purging Womb",
        description: "The womb erupts. Contractions, upheavals, and divine chaos lead to transformation.",
        taboos: &["Avoid resisting necessary emotional release"],
        prescriptions: &["Scream or cry into a river", "Clean your space with salt water"],
        orisha: &["Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Executed Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 56, binary: 0b00111000,
        name: "Òdí Méjì / Ògúndá Méjì",
        archetype: "The Ancestral Matriarch",
        description: "Blood memory awakens. Emotional intuition fuses with action — warrior wisdom passed through wombs.",
        taboos: &["Avoid disconnecting from your lineage"],
        prescriptions: &["Trace your maternal lineage three generations back", "Offer red clay and fire to Ògún"],
        orisha: &["Ògún", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Broken Storm",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 57, binary: 0b00111001,
        name: "Òdí Méjì / Òsá Méjì",
        archetype: "The Storm Bearer",
        description: "Storm in the womb. Thunder of prophecy, emotional unpredictability, and sacred rage.",
        taboos: &["Avoid storing unspoken truths"],
        prescriptions: &["Drum while barefoot in the rain", "Speak truth aloud under thunder"],
        orisha: &["Ọ̀yá", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 58, binary: 0b00111010,
        name: "Òdí Méjì / Ìkà Méjì",
        archetype: "The Poison Priestess",
        description: "Wounded emotions become power. Venom and healing — pain becomes sacred through ritual.",
        taboos: &["Avoid emotional manipulation"],
        prescriptions: &["Create an altar with snake imagery", "Transmute a painful memory into a dance"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 59, binary: 0b00111011,
        name: "Òdí Méjì / Òtúrúpòn Méjì",
        archetype: "The Creative Disruptor",
        description: "Emotional entropy. Chaos born from repression — healing lies in creative disorder.",
        taboos: &["Avoid strict emotional control"],
        prescriptions: &["Do seven spontaneous acts of beauty", "Break a clay pot intentionally and bury it"],
        orisha: &["Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 60, binary: 0b00111100,
        name: "Òdí Méjì / Òtúrá Méjì",
        archetype: "The Emotional Architect",
        description: "Structure around feeling. The architecture of emotional discipline and sacred rest.",
        taboos: &["Avoid abandoning emotional rituals"],
        prescriptions: &["Establish a seven-day cleansing cycle", "Map your emotional responses to the moon"],
        orisha: &["Ọ̀rúnmìlà", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 61, binary: 0b00111101,
        name: "Òdí Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Tidal Mother",
        description: "The slow birth. Emotions reveal themselves over time, not force — the patience of tides.",
        taboos: &["Avoid rushing sacred healing"],
        prescriptions: &["Offer four blue stones to the ocean", "Recite your lineage as a mantra"],
        orisha: &["Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Fractal Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 62, binary: 0b00111110,
        name: "Òdí Méjì / Òsé Méjì",
        archetype: "The Siren Priestess",
        description: "Seductive depth. The pleasure in surrendering emotionally — softness as sacred intelligence.",
        taboos: &["Avoid emotional detachment as defense"],
        prescriptions: &["Wear something sensual and flow with feeling", "Pray in warm water with honey and rose petals"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },

    Odu { index: 63, binary: 0b00111111,
        name: "Òdí Méjì / Òfún Méjì",
        archetype: "The Illuminated Womb",
        description: "The womb becomes light. Emotional mastery reveals divinity — illumination through deep feeling.",
        taboos: &["Avoid denying your spiritual gifts"],
        prescriptions: &["Pour libations while naming your gifts", "Clean your altar with milk and prayer"],
        orisha: &["Ọbàtálá", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Loop",
        vessel: ActionVessel::Loop,
        opcode: OduOpCode::Swap },
];
