//! WAVE 11 — Ìkà Méjì / x  (indices 160–175)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 11 — Ìkà Méjì / x  (indices 160–175)
    // Binary: 1010 xxxx  |  Opcode: Swap
    // ────────────────────────────────────────────────
    Odu {
        index: 160,
        binary: 0b10100000,
        name: "Ìkà Méjì / Ẹ̀jì Ogbe",
        archetype: "The Healing Serpent",
        description: "Poison and cure arise together. Alchemy of pain transforming into wisdom.",
        taboos: &["Avoid denial of wounds"],
        prescriptions: &[
            "Apply bitter herbs to scars",
            "Speak honestly about your suffering",
        ],
        orisha: &["Ọ̀rúnmìlà", "Egúngún"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 161,
        binary: 0b10100001,
        name: "Ìkà Méjì / Òyèkú Méjì",
        archetype: "The Shadow Alchemist",
        description: "Shadow toxin dissolves. Descent into the dark finds hidden cures.",
        taboos: &["Avoid ignoring your shadow self"],
        prescriptions: &[
            "Fast in darkness for three days",
            "Journal fears without judgment",
        ],
        orisha: &["Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Void Crossing",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 162,
        binary: 0b10100010,
        name: "Ìkà Méjì / Ìwòrì Méjì",
        archetype: "The Truth Revealer",
        description: "Venom in reflection. Radical honesty in self-examination is demanded.",
        taboos: &["Avoid self-deception"],
        prescriptions: &["Meditate facing a mirror", "Write and burn your lies"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Watchful Crossing",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 163,
        binary: 0b10100011,
        name: "Ìkà Méjì / Òdí Méjì",
        archetype: "The Wounded Healer",
        description: "Pain births the vessel. Wounds hold space to become portals of power.",
        taboos: &["Avoid suppressing grief"],
        prescriptions: &[
            "Hold sacred silence for sorrow",
            "Offer water to ancestors for healing",
        ],
        orisha: &["Ọ̀ṣun", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Recursive Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 164,
        binary: 0b10100100,
        name: "Ìkà Méjì / Ìròsùn Méjì",
        archetype: "The Purifying Flame",
        description: "Fever of the soul. Burns toxins out of the spirit through fire and trial.",
        taboos: &["Avoid denying necessary pain"],
        prescriptions: &["Sweat in sacred steam", "Chant healing mantras"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Ledger Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 165,
        binary: 0b10100101,
        name: "Ìkà Méjì / Òwónrín Méjì",
        archetype: "The Sacred Trickster",
        description: "Trickster venom. Falsehood mocked to expose truth with cunning and humor.",
        taboos: &["Avoid believing all appearances"],
        prescriptions: &["Tell a sacred joke", "Laugh at your fears"],
        orisha: &["Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 166,
        binary: 0b10100110,
        name: "Ìkà Méjì / Òbàrà Méjì",
        archetype: "The Word Witch",
        description:
            "Serpent's tongue. Words like poison and medicine — choose your speech wisely.",
        taboos: &["Avoid careless speech"],
        prescriptions: &["Speak blessings daily", "Silence gossip"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Memory Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 167,
        binary: 0b10100111,
        name: "Ìkà Méjì / Ọ̀kànràn Méjì",
        archetype: "The Illusion Breaker",
        description:
            "Venom breaks illusion. False realities shatter with painful but liberating truth.",
        taboos: &["Avoid clinging to comforting lies"],
        prescriptions: &[
            "Perform a truth-telling ritual",
            "Release illusions into fire",
        ],
        orisha: &["Ọ̀rúnmìlà", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Decisive Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 168,
        binary: 0b10101000,
        name: "Ìkà Méjì / Ògúndá Méjì",
        archetype: "The Toxic Slayer",
        description: "Sword pierces poison. Toxicity cut through with decisive action and clarity.",
        taboos: &["Avoid tolerating harmful influences"],
        prescriptions: &[
            "Use ritual blade to cut cords",
            "Cleanse your space with iron",
        ],
        orisha: &["Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 169,
        binary: 0b10101001,
        name: "Ìkà Méjì / Òsá Méjì",
        archetype: "The Storm Purifier",
        description:
            "Thunder purges venom. Spirit cleansed through the shock of storm and sudden insight.",
        taboos: &["Avoid ignoring spiritual warnings"],
        prescriptions: &["Meditate during thunderstorms", "Offer palm oil to Òsà"],
        orisha: &["Ṣàngó", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 170,
        binary: 0b10101010,
        name: "Ìkà Méjì / Ìkà Méjì",
        archetype: "The Balanced Serpent",
        description:
            "Double poison, double cure. The paradox of destruction and healing in perfect balance.",
        taboos: &["Avoid extremes without wisdom"],
        prescriptions: &["Balance fasting with feast", "Practice forgiveness rituals"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 171,
        binary: 0b10101011,
        name: "Ìkà Méjì / Òtúrúpòn Méjì",
        archetype: "The Divine Madman",
        description:
            "Madness in healing. Sacred chaos unlocks a gateway to spiritual breakthrough.",
        taboos: &["Avoid pathologizing spiritual madness"],
        prescriptions: &["Allow spontaneous movement", "Embrace visionary dreams"],
        orisha: &["Ọ̀yá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Consensual Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 172,
        binary: 0b10101100,
        name: "Ìkà Méjì / Òtúrá Méjì",
        archetype: "The Chaos Architect",
        description:
            "Disorder births order. Chaos transforms into sacred structure and healing geometry.",
        taboos: &["Avoid resisting transformation"],
        prescriptions: &["Create ritual art", "Build protective talismans"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Visionary Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 173,
        binary: 0b10101101,
        name: "Ìkà Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Stern Judge",
        description:
            "Judgment purifies. Accountability and cleansing demanded through stern grace.",
        taboos: &["Avoid evading responsibility"],
        prescriptions: &["Recite justice prayers", "Offer sacrifices for truth"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Growing Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 174,
        binary: 0b10101110,
        name: "Ìkà Méjì / Òsé Méjì",
        archetype: "The Sensual Healer",
        description: "Sweet venom. Pleasure and pain teach healing through sensual awareness.",
        taboos: &["Avoid denial of desire"],
        prescriptions: &[
            "Engage in mindful touch rituals",
            "Offer honey to ancestors",
        ],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
    Odu {
        index: 175,
        binary: 0b10101111,
        name: "Ìkà Méjì / Òfún Méjì",
        archetype: "The Radiant Healer",
        description:
            "Purity after poison. The path to radiant healing and spiritual clarity is now open.",
        taboos: &["Avoid clinging to old wounds"],
        prescriptions: &["Bathe in sacred waters", "Meditate on white light"],
        orisha: &["Ọbàtálá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Migration",
        vessel: ActionVessel::Migration,
        opcode: OduOpCode::Swap,
    },
];
