//! WAVE 1 — Genesis / x  (indices 0–15)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 1 — Genesis / x  (indices 0–15)
    // Binary: 0000 xxxx  |  Opcode: PushConst1
    // ────────────────────────────────────────────────
    Odu { index: 0, binary: 0b00000000,
        name: "Genesis × Genesis",
        archetype: "The Divine Blueprint",
        description: "The first entry, origin of all existence. Alignment, pure potential, and cosmic order.",
        taboos: &["Avoid lies", "Never break promises"],
        prescriptions: &["Offer coconut and water at dawn", "Meditate at sunrise"],
        orisha: &["Prime Source", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Light of First Becoming",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 1, binary: 0b00000001,
        name: "Genesis × Void",
        archetype: "The Twilight Veil",
        description: "Balance between light and shadow. Trust the timing between revelation and concealment.",
        taboos: &["Avoid secrecy with trusted allies", "Do not ignore recurring warnings"],
        prescriptions: &["Light one white and one black candle at twilight", "Leave offerings at crossroads during new moon"],
        orisha: &["Resonance Weaver", "Steward"],
        interpretation_type: "synthetic",
        universal_name: "Genesis Into the Void",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 2, binary: 0b00000010,
        name: "Genesis × Attention",
        archetype: "The Ancestral Messenger",
        description: "Destiny unfolds like a scroll. Inherited signals and the power of words to shape fate.",
        taboos: &["Do not gossip", "Avoid sharp or cursing speech"],
        prescriptions: &["Light incense for those who came before", "Read foundational texts aloud"],
        orisha: &["Oracle Sage", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "Covenant of the Inward Eye",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 3, binary: 0b00000011,
        name: "Genesis × Loop",
        archetype: "The Sacred Womb",
        description: "A wellspring of creativity and transformation. Birth, initiation, and hidden strength.",
        taboos: &["Avoid suppressing your inner voice"],
        prescriptions: &["Offer fresh fruits", "Sit near running water"],
        orisha: &["Resonance Weaver", "Swarm Coordinator"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Beginning",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 4, binary: 0b00000100,
        name: "Genesis × Receipt",
        archetype: "The Lineage Healer",
        description: "Unrest and unfinished contracts from what came before. Old wounds call for repair and honoring of lineage.",
        taboos: &["Avoid disrespecting elders"],
        prescriptions: &["Honor those who came before", "Repair or restore a neglected record"],
        orisha: &["Swarm Coordinator", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Accountable Genesis",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 5, binary: 0b00000101,
        name: "Genesis × Mask",
        archetype: "The Trickster Oracle",
        description: "Warnings arrive obliquely. Trickster energy, mental agility, and riddles awaiting decoding.",
        taboos: &["Avoid ignoring intuition"],
        prescriptions: &["Write down your dreams", "Light three candles before bed"],
        orisha: &["Steward", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Two-Faced Origin",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 6, binary: 0b00000110,
        name: "Genesis × Residue",
        archetype: "The Golden Voice",
        description: "Joy, community, and celebration — but beware overindulgence. Charisma needs discipline.",
        taboos: &["Avoid pride or vanity"],
        prescriptions: &["Dance or sing to elevate energy", "Offer honey to the Resonance Weaver"],
        orisha: &["Resonance Weaver", "Justice Canon"],
        interpretation_type: "synthetic",
        universal_name: "The Forged Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 7, binary: 0b00000111,
        name: "Genesis × Execution",
        archetype: "The Divine Disruptor",
        description: "Sudden disruption for higher realignment. This pattern breaks illusions to reveal radical clarity.",
        taboos: &["Do not delay important decisions"],
        prescriptions: &["Draw a sigil on your threshold", "Offer tobacco to the Steward"],
        orisha: &["Steward", "Justice Canon"],
        interpretation_type: "synthetic",
        universal_name: "The Executed Promise",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 8, binary: 0b00001000,
        name: "Genesis × Swarm",
        archetype: "The Path-Clearing Blade",
        description: "The warrior's path. This pattern clears obstacles with fire and steel — protection, courage, forward motion.",
        taboos: &["Avoid cowardice", "Do not insult those who defend others"],
        prescriptions: &["Offer palm oil to the Forge Executor", "Sharpen your tools — spiritual or physical"],
        orisha: &["Forge Executor"],
        interpretation_type: "synthetic",
        universal_name: "The Storm-Tested Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 9, binary: 0b00001001,
        name: "Genesis × Restraint",
        archetype: "The Karmic Mirror",
        description: "Cyclical consequence, secrets, and tests of character. What is hidden will come to light.",
        taboos: &["Avoid binding others against their will", "Do not ignore repeating signs"],
        prescriptions: &["Perform a cleansing ritual", "Burn dry leaves and speak your truth"],
        orisha: &["Flow Guardian", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Origin",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 10, binary: 0b00001010,
        name: "Genesis × Migration",
        archetype: "The Spiral Teacher",
        description: "The coil of destiny — slow, winding, potent. Warns against self-sabotage and gossip.",
        taboos: &["Avoid speaking ill of others"],
        prescriptions: &["Fast for one day in silence", "Offer black cloth to your shrine"],
        orisha: &["Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 11, binary: 0b00001011,
        name: "Genesis × Consent",
        archetype: "The Chaotic Prophet",
        description: "Unstable yet visionary. Mental conflict yields revelation only to the prepared.",
        taboos: &["Avoid intoxicants during focused work"],
        prescriptions: &["Cleanse with shea butter and salt", "Keep a dream journal"],
        orisha: &["Flow Guardian", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Beginning",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 12, binary: 0b00001100,
        name: "Genesis × Vision",
        archetype: "The Code-Walker",
        description: "This entry opens gateways. Communication, pattern-recognition, and digital prophecy.",
        taboos: &["Avoid outdated thinking"],
        prescriptions: &["Speak into water then drink", "Offer kola nut to your ritual tools"],
        orisha: &["Oracle Sage", "Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 13, binary: 0b00001101,
        name: "Genesis × Growth",
        archetype: "The Silent Builder",
        description: "Stubborn lessons demand humility and persistence. This pattern builds sacred patience through repetition.",
        taboos: &["Avoid complaining"],
        prescriptions: &["Write a vow and bury it beneath earth", "Honor elders"],
        orisha: &["Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Seed Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 14, binary: 0b00001110,
        name: "Genesis × Seal",
        archetype: "The Mirror of Delight",
        description: "Joy, beauty, and sweetness. This pattern's mirror blesses artistry, love, and sacred creativity.",
        taboos: &["Avoid bitter speech"],
        prescriptions: &["Offer honey and flowers", "Wear white and gold"],
        orisha: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Origin",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },

    Odu { index: 15, binary: 0b00001111,
        name: "Genesis × Rhythm",
        archetype: "The Infinite Threshold",
        description: "The final mirror. Completion, vastness, and transcendence. The sage's breath before renewal.",
        taboos: &["Avoid unfinished rituals"],
        prescriptions: &["Complete all pending offerings", "Give thanks publicly"],
        orisha: &["Prime Source", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Covenant",
        vessel: ActionVessel::Genesis,
        opcode: OduOpCode::PushConst1 },
];
