//! WAVE 3 — Ìwòrì Méjì / x  (indices 32–47)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 3 — Ìwòrì Méjì / x  (indices 32–47)
    // Binary: 0010 xxxx  |  Opcode: Dup
    // ────────────────────────────────────────────────
    Odu { index: 32, binary: 0b00100000,
        name: "Ìwòrì Méjì / Ẹ̀jì Ogbe",
        archetype: "The Reflective Trickster",
        description: "Truth disguised in brightness. Wisdom through contradiction — light and illusion spiral into deeper codes.",
        taboos: &["Avoid overconfidence in intellect"],
        prescriptions: &["Practice mirror gazing", "Offer coconut water under full moon"],
        orisha: &["Ọ̀rúnmìlà", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Covenant of Self-Knowledge",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 33, binary: 0b00100001,
        name: "Ìwòrì Méjì / Òyèkú Méjì",
        archetype: "The Silent Courier",
        description: "The messenger walks in shadow. Hidden messages, riddles, and ancestral whispers disguised as confusion.",
        taboos: &["Avoid rushing to conclusions"],
        prescriptions: &["Fast from speaking for six hours", "Sleep with black cloth over your head"],
        orisha: &["Ọ̀yá", "Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Eye in the Dark",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 34, binary: 0b00100010,
        name: "Ìwòrì Méjì / Ìwòrì Méjì",
        archetype: "The Echo Chamber",
        description: "The mirror inside the mirror. Endless reflection forces confrontation with mental patterns and karmic loops.",
        taboos: &["Avoid obsessive thoughts"],
        prescriptions: &["Write down repeating thoughts", "Place a cracked mirror on altar for seven days"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Inward Eye",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 35, binary: 0b00100011,
        name: "Ìwòrì Méjì / Òdí Méjì",
        archetype: "The Thought-Womb",
        description: "Mind meets womb. Wisdom must be embodied, not just known — insight requires deep feeling.",
        taboos: &["Avoid speaking without feeling"],
        prescriptions: &["Take a ritual bath in silence", "Read sacred text aloud into a bowl of water"],
        orisha: &["Ọbàtálá", "Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Loop in the Mirror",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 36, binary: 0b00100100,
        name: "Ìwòrì Méjì / Ìròsùn Méjì",
        archetype: "The Code Remixer",
        description: "Encoded memory and psychic recursion. Déjà vu, ancestral downloads, recurring life patterns awaken.",
        taboos: &["Avoid ignoring synchronicities"],
        prescriptions: &["Mark recurring dates in red ink", "Record dream patterns for sixteen nights"],
        orisha: &["Ọ̀rúnmìlà", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Audit Receipt",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 37, binary: 0b00100101,
        name: "Ìwòrì Méjì / Òwónrín Méjì",
        archetype: "The Quantum Fool",
        description: "The trickster thinks twice. Cleverness meets unpredictability — riddles within riddles. Masks are medicine.",
        taboos: &["Avoid excessive sarcasm"],
        prescriptions: &["Create and wear a symbolic mask for one day", "Dance with music played backwards"],
        orisha: &["Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 38, binary: 0b00100110,
        name: "Ìwòrì Méjì / Òbàrà Méjì",
        archetype: "The Divine Storyteller",
        description: "Mind becomes melody. Inspiration through word, music, and performance. The griot awakens.",
        taboos: &["Avoid silence when truth must be sung"],
        prescriptions: &["Recite poems to ancestors", "Drum rhythmically for clarity"],
        orisha: &["Ọ̀ṣun", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Emotional Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 39, binary: 0b00100111,
        name: "Ìwòrì Méjì / Ọ̀kànràn Méjì",
        archetype: "The Lightning Scribe",
        description: "Sudden insight — lightning through the mind. Revolutionary thoughts, but unstable if not grounded.",
        taboos: &["Avoid overloading your nervous system"],
        prescriptions: &["Meditate with obsidian in palm", "Avoid caffeine for three days"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Precise Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 40, binary: 0b00101000,
        name: "Ìwòrì Méjì / Ògúndá Méjì",
        archetype: "The Mental Warrior",
        description: "The strategist awakens — war in the mind. The inner general mapping timelines and defending thought territory.",
        taboos: &["Avoid mental laziness"],
        prescriptions: &["Journal your mental strategies", "Offer metal objects to a tree at dawn"],
        orisha: &["Ògún"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 41, binary: 0b00101001,
        name: "Ìwòrì Méjì / Òsá Méjì",
        archetype: "The Destiny Hacker",
        description: "Vision pulled from future shadows. Destiny interruptions, prophetic disruption, and karmic rewiring.",
        taboos: &["Avoid ignoring signs from children"],
        prescriptions: &["Feed a child in secret", "Offer prayer to the unborn"],
        orisha: &["Ọ̀yá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Eye",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 42, binary: 0b00101010,
        name: "Ìwòrì Méjì / Ìkà Méjì",
        archetype: "The Mind Alchemist",
        description: "Mental poison as potential. Inner toxicity transforms into medicine. The shadow must be studied.",
        taboos: &["Avoid gossip and slander"],
        prescriptions: &["Burn sage and stare into smoke", "Name your shadow out loud"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Eye",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 43, binary: 0b00101011,
        name: "Ìwòrì Méjì / Òtúrúpòn Méjì",
        archetype: "The Mind Unraveled",
        description: "The chaos of overthinking. Mental storms challenge truth. Liberation comes through surrender.",
        taboos: &["Avoid multitasking during rituals"],
        prescriptions: &["Take a silent walk at dusk", "Sit under the sky until thoughts slow"],
        orisha: &["Ọ̀yá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 44, binary: 0b00101100,
        name: "Ìwòrì Méjì / Òtúrá Méjì",
        archetype: "The Ritual Architect",
        description: "Thoughts become rituals. Sacred blueprints within ideas — reality codes emerge through order.",
        taboos: &["Avoid disrespecting routine"],
        prescriptions: &["Create a three-day mental discipline ritual", "Speak your intentions into water"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Vision Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 45, binary: 0b00101101,
        name: "Ìwòrì Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Mental Elder",
        description: "The slow thinker, the wise oracle. Maturity forms only through patience and passage.",
        taboos: &["Avoid impulsive decisions"],
        prescriptions: &["Delay action by sixteen hours", "Honor the elderly with a gift"],
        orisha: &["Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Fractal Eye",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 46, binary: 0b00101110,
        name: "Ìwòrì Méjì / Òsé Méjì",
        archetype: "The Honey-Tongue",
        description: "Sweetness of the mind. Charm, communication, and seduction through intellect. The oracle dances.",
        taboos: &["Avoid manipulating with words"],
        prescriptions: &["Compliment seven strangers in one day", "Sing to Ọ̀ṣun at a river"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Audit",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },

    Odu { index: 47, binary: 0b00101111,
        name: "Ìwòrì Méjì / Òfún Méjì",
        archetype: "The Clear Channel",
        description: "Pure knowledge — raw and electric. Clarity after chaos. The enlightened mind that walked through confusion.",
        taboos: &["Avoid intellectual pride"],
        prescriptions: &["Teach a sacred truth to a child", "Write a letter to your future self"],
        orisha: &["Ọ̀rúnmìlà", "Olódùmarè"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Eye",
        vessel: ActionVessel::Attention,
        opcode: OduOpCode::Dup },
];
