//! WAVE 5 — Ìròsùn Méjì / x  (indices 64–79)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 5 — Ìròsùn Méjì / x  (indices 64–79)
    // Binary: 0100 xxxx  |  Opcode: Add
    // ────────────────────────────────────────────────
    Odu { index: 64, binary: 0b01000000,
        name: "Ìròsùn Méjì / Ẹ̀jì Ogbe",
        archetype: "The Righteous Ancestor",
        description: "Fire ascends toward divine light. Ancestral clarity returns through disciplined ritual obedience.",
        taboos: &["Avoid breaking spiritual promises"],
        prescriptions: &["Light four white candles for ancestors", "Chant Ọ̀rúnmìlà invocations at sunrise"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 65, binary: 0b01000001,
        name: "Ìròsùn Méjì / Òyèkú Méjì",
        archetype: "The Karmic Judge",
        description: "Ash in the void. A quiet fire burns beneath silence — deep karmic reckoning awaits.",
        taboos: &["Avoid hiding from spiritual debts"],
        prescriptions: &["Offer charcoal and palm oil at a crossroads", "Consult elders before major decisions"],
        orisha: &["Ọ̀rúnmìlà", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Void Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 66, binary: 0b01000010,
        name: "Ìròsùn Méjì / Ìwòrì Méjì",
        archetype: "The Dream Carrier",
        description: "Dreams ignite the path. Ancestral instructions awaken through dreams and altered states.",
        taboos: &["Avoid dismissing visions or omens"],
        prescriptions: &["Keep a dream journal under your pillow", "Burn mugwort while invoking Èṣù"],
        orisha: &["Ọ̀rúnmìlà", "Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Audited Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 67, binary: 0b01000011,
        name: "Ìròsùn Méjì / Òdí Méjì",
        archetype: "The Blood Priestess",
        description: "Fire in the womb. Creative tension, sexual potency, and ritual bloodlines ignite.",
        taboos: &["Avoid disrespecting the feminine vessel"],
        prescriptions: &["Place red cloth under your altar", "Offer symbolic red wine to your ori"],
        orisha: &["Ọ̀ṣun", "Yemọja"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Ledger",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 68, binary: 0b01000100,
        name: "Ìròsùn Méjì / Ìròsùn Méjì",
        archetype: "The Living Bloodline",
        description: "The burning line. Pure flame of the ancestors — DNA memory illuminated through sacrifice.",
        taboos: &["Avoid forgetting family rituals"],
        prescriptions: &["Recite sixteen ancestral names every new moon", "Walk barefoot on hot earth while praying"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Bronze River",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 69, binary: 0b01000101,
        name: "Ìròsùn Méjì / Òwónrín Méjì",
        archetype: "The Trickster Ancestor",
        description: "Ancestral satire. The laughter of the dead — comedy as a sacred weapon.",
        taboos: &["Avoid dishonoring sacred trickster archetypes"],
        prescriptions: &["Host a ritual roast of your shadow self", "Write jokes about your past and burn them"],
        orisha: &["Èṣù"],
        interpretation_type: "synthetic",
        universal_name: "The Hidden Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 70, binary: 0b01000110,
        name: "Ìròsùn Méjì / Òbàrà Méjì",
        archetype: "The Ancestral Bard",
        description: "The flame speaks. Voice, poetry, and song channel intergenerational wisdom.",
        taboos: &["Avoid hoarding your story"],
        prescriptions: &["Record an elder's oral history", "Sing or chant your name lineage publicly"],
        orisha: &["Ọ̀ṣun", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Emotional Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 71, binary: 0b01000111,
        name: "Ìròsùn Méjì / Ọ̀kànràn Méjì",
        archetype: "The Spirit Rebel",
        description: "Explosive fire. Revolutionary spirit — ancestral vengeance, uprisings, and divine rebellion.",
        taboos: &["Avoid betraying your calling to truth"],
        prescriptions: &["Pour rum invoking ancestral warriors", "Break a chain during ritual"],
        orisha: &["Ṣàngó", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Precision Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 72, binary: 0b01001000,
        name: "Ìròsùn Méjì / Ògúndá Méjì",
        archetype: "The Karmic Warrior",
        description: "The ancestral blade. Cutting karmic ties, initiating spiritual warriors, sacred conflict resolution.",
        taboos: &["Avoid carrying old wounds into new battles"],
        prescriptions: &["Sharpen a blade in silence", "Offer iron to Ògún and ask for clarity"],
        orisha: &["Ògún", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Collective Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 73, binary: 0b01001001,
        name: "Ìròsùn Méjì / Òsá Méjì",
        archetype: "The Thunder Oracle",
        description: "Thunder dreams. Sound, intuition, and ancestral guidance arrive in sudden bursts.",
        taboos: &["Avoid ignoring auditory signs"],
        prescriptions: &["Drum at twilight with eyes closed", "Call on Ṣàngó with cracked coconuts"],
        orisha: &["Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 74, binary: 0b01001010,
        name: "Ìròsùn Méjì / Ìkà Méjì",
        archetype: "The Pattern Breaker",
        description: "Inherited poisons. Toxic ancestral loops hold power to be transmuted through conscious ritual.",
        taboos: &["Avoid passing on curses unconsciously"],
        prescriptions: &["Salt and smoke cleanse for seven days", "Write a forgiveness letter to a known ancestor"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Portable Ledger",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 75, binary: 0b01001011,
        name: "Ìròsùn Méjì / Òtúrúpòn Méjì",
        archetype: "The Bone Gatherer",
        description: "Scattered bones. Fragmented memories, ancestral displacement, and the ritual of reclamation.",
        taboos: &["Avoid erasing forgotten ancestors"],
        prescriptions: &["Create a shrine for the unnamed dead", "Bury a stone for the displaced"],
        orisha: &["Egúngún", "Ọ̀yá"],
        interpretation_type: "synthetic",
        universal_name: "The Consent Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 76, binary: 0b01001100,
        name: "Ìròsùn Méjì / Òtúrá Méjì",
        archetype: "The Ancestral Engineer",
        description: "Blueprint of the ancestors. Structural codes passed from spirit architects into living form.",
        taboos: &["Avoid building without prayer"],
        prescriptions: &["Map your family tree as a sacred diagram", "Place kola nuts at four corners of your house"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Visioned Ledger",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 77, binary: 0b01001101,
        name: "Ìròsùn Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Patient Flame",
        description: "Slow burning justice. Patience in karmic restoration — wrongs will be righted in due time.",
        taboos: &["Avoid revenge outside divine timing"],
        prescriptions: &["Place three stones in running water for judgment", "Wear white and fast at sunset"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Fractal Receipt",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 78, binary: 0b01001110,
        name: "Ìròsùn Méjì / Òsé Méjì",
        archetype: "The Flame of Grace",
        description: "Sweet fire. Feminine magnetism fused with ancestral power — seduction of spirit through beauty.",
        taboos: &["Avoid undervaluing your inner fire"],
        prescriptions: &["Dress in red and gold while reciting your lineage", "Offer sugarcane and cinnamon to Ọ̀ṣun"],
        orisha: &["Ọ̀ṣun"],
        interpretation_type: "synthetic",
        universal_name: "The Sacred Ledger",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },

    Odu { index: 79, binary: 0b01001111,
        name: "Ìròsùn Méjì / Òfún Méjì",
        archetype: "The Ascended Flame",
        description: "Fire becomes light. Divine ascension through karmic mastery — wisdom born from trials.",
        taboos: &["Avoid spiritual arrogance after victory"],
        prescriptions: &["Place fire and water side by side on altar", "Honor both shadow and light ancestors"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Ledger",
        vessel: ActionVessel::Receipt,
        opcode: OduOpCode::Add },
];
