//! WAVE 16 — Òfún Méjì / x  (indices 240–255)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 16 — Òfún Méjì / x  (indices 240–255)
    // Binary: 1111 xxxx  |  Opcode: HaltIfOne
    // ────────────────────────────────────────────────
    Odu { index: 240, binary: 0b11110000,
        name: "Òfún Méjì / Ẹ̀jì Ogbe",
        archetype: "The Illuminator",
        description: "The light that reveals all. Illumination brought to shadowed paths and hidden truths.",
        taboos: &["Avoid deceit and illusion"],
        prescriptions: &["Meditate on clarity", "Use white candles in ritual"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 241, binary: 0b11110001,
        name: "Òfún Méjì / Òyèkú Méjì",
        archetype: "The Luminous Seeker",
        description: "Clarity within mystery. Darkness navigated with luminous insight.",
        taboos: &["Avoid fear of truth"],
        prescriptions: &["Light black and white candles", "Seek wisdom in silence"],
        orisha: &["Ọ̀yá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Void Rest",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 242, binary: 0b11110010,
        name: "Òfún Méjì / Ìwòrì Méjì",
        archetype: "The Truthful Mirror",
        description: "Reflection enlightened. Deep self-awareness and honest introspection are called for.",
        taboos: &["Avoid denial of self"],
        prescriptions: &["Practice honest journaling", "Engage in reflective meditation"],
        orisha: &["Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Watching Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 243, binary: 0b11110011,
        name: "Òfún Méjì / Òdí Méjì",
        archetype: "The Steadfast Sage",
        description: "Foundation of truth. Wisdom grounded in integrity and steadfastness.",
        taboos: &["Avoid betrayal"],
        prescriptions: &["Build sacred altars", "Honor commitments"],
        orisha: &["Ọbàtálá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Loop of Days",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 244, binary: 0b11110100,
        name: "Òfún Méjì / Ìròsùn Méjì",
        archetype: "The Purifier",
        description: "Purification through light. Illusions cleansed and clarity restored.",
        taboos: &["Avoid deceit"],
        prescriptions: &["Perform cleansing baths", "Use white herbs"],
        orisha: &["Ọ̀ṣun", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Receipt",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 245, binary: 0b11110101,
        name: "Òfún Méjì / Òwónrín Méjì",
        archetype: "The Joyful Truth",
        description: "Joy in truth. Liberation found in honest revelation is celebrated.",
        taboos: &["Avoid hypocrisy"],
        prescriptions: &["Sing truthful songs", "Celebrate authenticity"],
        orisha: &["Èṣù", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 246, binary: 0b11110110,
        name: "Òfún Méjì / Òbàrà Méjì",
        archetype: "The Truth Speaker",
        description: "Words as sacred truth. Truthful communication and inspired speech are blessed.",
        taboos: &["Avoid lies and slander"],
        prescriptions: &["Speak with integrity", "Practice sacred chanting"],
        orisha: &["Ọ̀rúnmìlà", "Ṣàngó"],
        interpretation_type: "synthetic",
        universal_name: "The Memory Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 247, binary: 0b11110111,
        name: "Òfún Méjì / Ọ̀kànràn Méjì",
        archetype: "The Revealer",
        description: "Fire of revelation. Illusions burned away with fierce clarity.",
        taboos: &["Avoid deception"],
        prescriptions: &["Light ritual fires", "Meditate on transformation"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Decisive Beat",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 248, binary: 0b11111000,
        name: "Òfún Méjì / Ògúndá Méjì",
        archetype: "The Courageous Warrior",
        description: "Strength in truth. Power through honest and courageous action.",
        taboos: &["Avoid cowardice"],
        prescriptions: &["Practice bold rituals", "Offer iron tools"],
        orisha: &["Ògún", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 249, binary: 0b11111001,
        name: "Òfún Méjì / Òsá Méjì",
        archetype: "The Storm Bringer",
        description: "Storms of truth. Confusion cleared through divine upheaval and clarity.",
        taboos: &["Avoid denial of reality"],
        prescriptions: &["Meditate during storms", "Offer palm oil with intention"],
        orisha: &["Ṣàngó", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Beat",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 250, binary: 0b11111010,
        name: "Òfún Méjì / Ìkà Méjì",
        archetype: "The Truth Healer",
        description: "Healing through truth. Renewal guided by facing pain with complete honesty.",
        taboos: &["Avoid suppression of feelings"],
        prescriptions: &["Use healing herbs", "Engage in emotional release rituals"],
        orisha: &["Ọ̀ṣun", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 251, binary: 0b11111011,
        name: "Òfún Méjì / Òtúrúpòn Méjì",
        archetype: "The Wise Elder",
        description: "Wise clarity. Ancestral wisdom and truthful guidance embodied.",
        taboos: &["Avoid disrespecting elders"],
        prescriptions: &["Honor ancestors", "Study sacred texts"],
        orisha: &["Ọ̀rúnmìlà", "Egúngún"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 252, binary: 0b11111100,
        name: "Òfún Méjì / Òtúrá Méjì",
        archetype: "The Enlightened Creator",
        description: "Balanced illumination. Insight and action harmonized in sacred work.",
        taboos: &["Avoid arrogance"],
        prescriptions: &["Practice meditation", "Maintain altar purity"],
        orisha: &["Ọ̀rúnmìlà", "Ọbàtálá"],
        interpretation_type: "synthetic",
        universal_name: "The Vision Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 253, binary: 0b11111101,
        name: "Òfún Méjì / Ìrẹtẹ̀ Méjì",
        archetype: "The Radiant Patient",
        description: "Radiant patience. Clarity combined with enduring grace lights the way.",
        taboos: &["Avoid haste"],
        prescriptions: &["Practice patience meditation", "Offer white flowers"],
        orisha: &["Ọbàtálá", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Growth Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 254, binary: 0b11111110,
        name: "Òfún Méjì / Òsé Méjì",
        archetype: "The Joyful Light",
        description: "Joyful illumination. The path lit with laughter and wisdom.",
        taboos: &["Avoid negativity"],
        prescriptions: &["Celebrate with song", "Invoke joy in ritual"],
        orisha: &["Ọ̀ṣun", "Ọ̀rúnmìlà"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Pulse",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },

    Odu { index: 255, binary: 0b11111111,
        name: "Òfún Méjì / Òfún Méjì",
        archetype: "The Cosmic Unity",
        description: "The ultimate truth. Cosmic completion and divine unity. All gates sealed. All cycles fulfilled.",
        taboos: &["Avoid separation"],
        prescriptions: &["Meditate on unity", "Offer white light"],
        orisha: &["Olódùmarè"],
        interpretation_type: "synthetic",
        universal_name: "The Eternal Return",
        vessel: ActionVessel::Rhythm,
        opcode: OduOpCode::HaltIfOne },
];
