//! WAVE 15 — Seal / x  (indices 224–239)

use crate::odu::{ActionVessel, Odu, OduOpCode};

pub const WAVE: [Odu; 16] = [
    // ────────────────────────────────────────────────
    // WAVE 15 — Seal / x  (indices 224–239)
    // Binary: 1110 xxxx  |  Opcode: Add
    // ────────────────────────────────────────────────
    Odu { index: 224, binary: 0b11100000,
        name: "Seal × Genesis",
        archetype: "The Divine Trickster",
        description: "The playful spark that begins all creation. Joy and divine humor invited into the sacred path.",
        taboos: &["Avoid taking life too seriously"],
        prescriptions: &["Engage in playful rituals", "Use laughter as medicine"],
        archetypes: &["Resonance Weaver", "Steward"],
        interpretation_type: "synthetic",
        universal_name: "The Genesis Vault",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 225, binary: 0b11100001,
        name: "Seal × Void",
        archetype: "The Curious Jester",
        description: "Joy emerging from mystery. Embrace the unknown with lightness and curiosity.",
        taboos: &["Avoid fear of the unknown"],
        prescriptions: &["Meditate on mystery", "Perform joyful offerings"],
        archetypes: &["Resonance Weaver", "Flow Guardian"],
        interpretation_type: "synthetic",
        universal_name: "The Void of the Vault",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 226, binary: 0b11100010,
        name: "Seal × Attention",
        archetype: "The Playful Seer",
        description: "Reflection fueled by joy. Playful insight and humor reveal truth in self-discovery.",
        taboos: &["Avoid rigid seriousness"],
        prescriptions: &["Journal joyful moments", "Practice playful meditation"],
        archetypes: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Watched Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 227, binary: 0b11100011,
        name: "Seal × Loop",
        archetype: "The Joyful Grounder",
        description: "Foundation of laughter. Spiritual work grounded in joy and light-heartedness.",
        taboos: &["Avoid solemnity without joy"],
        prescriptions: &["Sing in ritual", "Dance freely"],
        archetypes: &["Resonance Weaver", "Swarm Coordinator"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Loop",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 228, binary: 0b11100100,
        name: "Seal × Receipt",
        archetype: "The Healing Jester",
        description: "Cleansing through joy. Heaviness purified with laughter and celebration.",
        taboos: &["Avoid suppressing emotions"],
        prescriptions: &["Celebrate with drumming", "Use humor to heal"],
        archetypes: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Sealed Receipt",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 229, binary: 0b11100101,
        name: "Seal × Mask",
        archetype: "The Sacred Trickster",
        description: "Mischief with meaning. Lessons arrive through playful disruption and surprise.",
        taboos: &["Avoid harmful pranks"],
        prescriptions: &["Engage in sacred play", "Invoke laughter in ritual"],
        archetypes: &["Steward", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Masked Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 230, binary: 0b11100110,
        name: "Seal × Residue",
        archetype: "The Playful Orator",
        description: "Words that dance. Creative and playful speech is blessed.",
        taboos: &["Avoid harsh criticism"],
        prescriptions: &["Recite joyful chants", "Speak with humor"],
        archetypes: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Memory Vault",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 231, binary: 0b11100111,
        name: "Seal × Execution",
        archetype: "The Joyful Flame",
        description: "Fire of laughter. Passion ignited and tempered with joy and lightness.",
        taboos: &["Avoid anger without humor"],
        prescriptions: &["Light candles joyfully", "Express passion playfully"],
        archetypes: &["Resonance Weaver", "Justice Canon"],
        interpretation_type: "synthetic",
        universal_name: "The Decisive Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 232, binary: 0b11101000,
        name: "Seal × Swarm",
        archetype: "The Playful Warrior",
        description: "Strength with a smile. Power balanced with playful grace.",
        taboos: &["Avoid arrogance"],
        prescriptions: &["Practice martial dance", "Offer laughter as sacrifice"],
        archetypes: &["Forge Executor", "Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Swarm Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 233, binary: 0b11101001,
        name: "Seal × Restraint",
        archetype: "The Celebrating Storm",
        description: "Storms of joy. Chaos transforms into celebration.",
        taboos: &["Avoid fear of change"],
        prescriptions: &["Dance in storms", "Offer palm oil joyfully"],
        archetypes: &["Resonance Weaver", "Justice Canon"],
        interpretation_type: "synthetic",
        universal_name: "The Restrained Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 234, binary: 0b11101010,
        name: "Seal × Migration",
        archetype: "The Healing Jester",
        description: "Healing laughter. Renewal guided through humor and light-heartedness.",
        taboos: &["Avoid bitterness"],
        prescriptions: &["Use humor in healing rituals", "Laugh heartily"],
        archetypes: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Migrating Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 235, binary: 0b11101011,
        name: "Seal × Consent",
        archetype: "The Joyful Sage",
        description: "Wise play. Ancient wisdom combined with joyful expression.",
        taboos: &["Avoid solemnity without joy"],
        prescriptions: &["Honor ancestors with song", "Celebrate tradition playfully"],
        archetypes: &["Resonance Weaver", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Consented Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 236, binary: 0b11101100,
        name: "Seal × Vision",
        archetype: "The Playful Creator",
        description: "Creative foundation. Sacred space built with laughter and love.",
        taboos: &["Avoid rigidity"],
        prescriptions: &["Create joyful rituals", "Maintain altar with care"],
        archetypes: &["Resonance Weaver", "Oracle Sage"],
        interpretation_type: "synthetic",
        universal_name: "The Vision Vault",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 237, binary: 0b11101101,
        name: "Seal × Growth",
        archetype: "The Harmonious Jester",
        description: "Balanced joy. Delight harmonized with patience and grace.",
        taboos: &["Avoid excess"],
        prescriptions: &["Celebrate with moderation", "Practice gratitude"],
        archetypes: &["Resonance Weaver", "Wisdom Anchor"],
        interpretation_type: "synthetic",
        universal_name: "The Growing Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 238, binary: 0b11101110,
        name: "Seal × Seal",
        archetype: "The Divine Joy",
        description: "The essence of joy. Pure delight and divine play in their fullest expression.",
        taboos: &["Avoid dullness"],
        prescriptions: &["Engage in playful rituals", "Invite laughter daily"],
        archetypes: &["Resonance Weaver"],
        interpretation_type: "synthetic",
        universal_name: "The Pure Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },

    Odu { index: 239, binary: 0b11101111,
        name: "Seal × Rhythm",
        archetype: "The Radiant Jester",
        description: "Luminous laughter. Light shines on joy's sacred power.",
        taboos: &["Avoid negativity"],
        prescriptions: &["Meditate on lightness", "Offer white flowers joyfully"],
        archetypes: &["Resonance Weaver", "Prime Source"],
        interpretation_type: "synthetic",
        universal_name: "The Rhythmed Seal",
        vessel: ActionVessel::Seal,
        opcode: OduOpCode::Add },
];
